### ISSUE TITLE
[TypeError: Converting circular structure to JSON] when try to send node js stream over tcp transport

### ISSUE THREAD

**Issue by vovantigo** [senecajs/seneca#252]
When use 

```
.client({ host: '...', port: ..., type: 'tcp', timeout: 30000, pin: { role: '...'} })
``` 
and set stream object as one of parameters in 

```
.act({ role: '...', stream: ..., ...}, ...) 
```

attempt to serialize to JSON (why?!) leads to error:

```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at DestroyableTransform._transform (D:\sr\DigitalLiving\modular\samples-services-minecare\node_modules\seneca\node_modules\seneca-transport\node_modules\ndjson\index.js:28:19)
    at DestroyableTransform.Transform._read (D:\sr\DigitalLiving\modular\samples-services-minecare\node_modules\seneca\node_modules\seneca-transport\node_modules\ndjson\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (D:\sr\DigitalLiving\modular\samples-services-minecare\node_modules\seneca\node_modules\seneca-transport\node_modules\ndjson\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (D:\sr\DigitalLiving\modular\samples-services-minecare\node_modules\seneca\node_modules\seneca-transport\node_modules\ndjson\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (D:\sr\DigitalLiving\modular\samples-services-minecare\node_modules\seneca\node_modules\seneca-transport\node_modules\ndjson\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (D:\sr\DigitalLiving\modular\samples-services-minecare\node_modules\seneca\node_modules\seneca-transport\node_modules\ndjson\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at Seneca.<anonymous> (D:\sr\DigitalLiving\modular\samples-services-minecare\node_modules\seneca\node_modules\seneca-transport\lib\tcp.js:107:23)
    at D:\sr\DigitalLiving\modular\samples-services-minecare\node_modules\seneca\node_modules\seneca-transport\lib\transport-utils.js:300:14
    at D:\sr\DigitalLiving\modular\samples-services-minecare\node_modules\seneca\node_modules\seneca-transport\lib\transport-utils.js:379:7
```

**Comment by mcdonnelldean** [comment]
This is because Seneca is going to set up your tcp connection, serialize your messages and send them on. Because you have a stream in there you get this issue. You would have to strip the stream out.

**Comment by geek** [comment]
We can be more defensive about stringifying.  However, the message itself should be JSON stringifiable.

**Comment by rjrodger** [comment]
it would be good to have a more explanatory error message when this occurs

**Comment by mcdonnelldean** [comment]
@vovantigo Generally we work over JSON since that is known to all transports. We are looking at adding the ability to swap out transport cores in the future so you can change this. I've made a note about the error being a bit terrible, we are fixing logging up in the next major version or too, see #397
