### ISSUE TITLE
Actions executed within plugins don't receive errors passed from other services

### ISSUE THREAD

**Issue by MatthewPikar** [senecajs/seneca#253]
Executing an action against a service seems to capture errors fine unless my client itself is packaged within a plugin.  If the service is packaged within a plugin, and a server passes back an error, the callback seems to not execute.

I set up a simple service like so:

[ **tmp.js** ]
```javascript
module.exports = function tmp(options) {
    var seneca = this;

    seneca
        .add({role: 'tmp', cmd: 'query'},
            function(args, done){
                if (args.test == "true")
                    return done(new Error("Error was created!!"), null);
                else
                    return done(null, {test:args.test});
            });
};
```
[ **tmpService.js** ]
```javascript
require('seneca')()
    .use('tmp.js')
    .listen({type:'tcp', port:'30010', pin:'role:tmp'});
```

If I run a simple client like so, the error seems to be handled properly:

[ **tmpApiService.js** ]
```javascript
var seneca = require('seneca')()
    .client({type:'tcp', port:'30010', pin:'role:tmp'})
    .act({role:'tmp', cmd:'query', test:"true"}, function(err, res){
        if (err)   console.error("\n\n" + "Back" + "\n\n" + err);
        else      console.log("\n\n" + "Back: no error" + "\n\n")
    });
```

BUT, if I package the client within a plugin, the error is not handled and crashes the client process:

[ **tmpApi.js** ]
```javascript
module.exports = function api(options) {
    var seneca = this;

    seneca.add({role:'api', cmd:'tmpQuery'},
        function(args, done) {
            seneca.act(({role: 'tmp', cmd: 'query', test: args.test}), done)
        })
};
```
[ **tmpApiService.js** ]
```javascript
var seneca = require('seneca')()
    .use('tmpApi.js')
    .client({type:'tcp', port:'30010', pin:'role:tmp'})

seneca.act({role:'api', cmd:'tmpQuery', test:"true"}, function(err, res){
    if (err)
        console.error("\n\n" + "Back" + "\n\n" + err);
    else
        console.log("\n\n" + "Back: " + res + "\n\n")
});
```

This fails if I try to handle the error within the "{role:'api', cmd:'tmpQuery'}" action as well.

Stepping through the code, it seems that the callback in the plugin case is never executed when the error is passed, but is executed when a non-error response if provided.

I'm sure I'm doing something wrong, but I just can't see it.

**Comment by rjrodger** [comment]
looks very much like a bug, and a fairly serious one
@geek 0.9.1 patch?

**Comment by geek** [comment]
@MatthewPikar I added a test in #273 ... it passes.  Do you mind trying to create a test for what you are describing?

**Comment by MatthewPikar** [comment]
Ok,

I uploaded 4 files, which are almost exactly what I wrote up above, except I replaced the API service with a mocha test script.  I ran the script against Seneca 0.9.2.

**tmp** - just looks for a test variable and passes back a new error  if it's "true".
> done(new Error("Error was created!!"))

**tmpService** - just turns tmp into a service

**tmpApi** - calls act(tmp) passing the test variable, looks for the returned error and returns "error caught!" if err is truthy.
> done(null, {message:"error caught!"})

**testscript** - calls act with the test variable and looks for "error caught!".

The test passes, but the error gets thrown regardless, which crashes the parent process.

[tmp.txt](https://github.com/senecajs/seneca/files/65924/tmp.txt)
[tmpApi.txt](https://github.com/senecajs/seneca/files/65925/tmpApi.txt)
[tmpService.txt](https://github.com/senecajs/seneca/files/65927/tmpService.txt)
[testscript.txt](https://github.com/senecajs/seneca/files/65928/testscript.txt)

Hope this helps.

**Comment by MatthewPikar** [comment]
Here is the error thrown, when I run the test:

> 2015-12-17T20:51:49.769Z 6kd1nd28rvmf/1450385509427/13534/- ERROR	act	client$       	OUT	role:tmp	5	{role:tmp,cmd:query,test:true}	ENTRY	(wd84u)	-	seneca: Action cmd:query,role:tmp failed: Error was created!!.	act_execute	{id:suibnnq4eicy/7i67nfiqz774,gate:false,ungate:true,desc:cmd:query,role:tmp,plugin:{name:tmp,tag:-},time:{star	Error: seneca: Action cmd:query,role:tmp failed: Error was created!!.
 
Of course, this is the error passed by **tmp**, but instead of being passed and handled it gets thrown.

**Comment by MatthewPikar** [comment]
As an aside, timeouts (ex: when tmpService is not running) also throw and can't be handled.

**Comment by geek** [comment]
@MatthewPikar I added your tests into the repo.  I am not able to reproduce where the error is thrown and crashes things.  Any ideas on how to make the tests fail with the case you are describing?

**Comment by MatthewPikar** [comment]
For sanity's sake I just re-ran the test on a clean install of seneca 0.9.2.  I was running node 4.2.2, but I just switched to 5.3 to see if the problem persists, and it does.  I'm not sure what other outside variables would affect the execution of the code.

The test does pass as the error seems to be thrown outside my code.  Below is the full test report.  I can look into the seneca code base and try to follow this into the rabbit hole, but I'm new to seneca, so not sure how well that will go.  It maybe more worthwhile for me to run seneca's tests and see if anything fails.  I'll you know how it goes.

Cheers!

----------------------------
2015-12-18T05:00:34.629Z 37sggwv8r3ec/1450414834611/847/- INFO	hello	Seneca/0.9.2/37sggwv8r3ec/1450414834611/847/-	
2015-12-18T05:00:34.849Z 37sggwv8r3ec/1450414834611/847/- INFO	client	{type:tcp,port:30010,pin:role:tmp}	


  seneca
    act
      ✓ should return "no errors created." when passing test false
2015-12-18T05:00:34.905Z 37sggwv8r3ec/1450414834611/847/- ERROR	act	client$       	OUT		role:tmp	9	{role:tmp,cmd:query,test:true}	ENTRY	(nkagr)	-	seneca: Action cmd:query,role:tmp failed: Error was created!!.	act_execute	{id:6rrv7b9lu24a/0zohgs5z65vc,gate:false,ungate:true,desc:cmd:query,role:tmp,plugin:{name:tmp,tag:-},time:{star	Error: seneca: Action cmd:query,role:tmp failed: Error was created!!.
    at internals.Utils.handle_response (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:79:11)
    at Duplex.messager._write (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/lib/tcp.js:146:19)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Duplex.Writable.write (_stream_writable.js:207:11)
    at write (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at push (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/split2/index.js:50:10)
    at DestroyableTransform.transform [as _transform] (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/split2/index.js:27:5)
    at DestroyableTransform.Transform._read (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/mattpiekarczyk/Documents/dev/untitled/node_modules/seneca/node_modules/seneca-transport/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)	
      ✓ should return "error caught!" when passing test true


  2 passing (52ms)

**Comment by MatthewPikar** [comment]
I ran all seneca's tests and got only one unrelated failure relating to CLI not displaying action patterns.  Looking through the transport tests it appears that they cover action errors, but not in the situation where the actions are within a plugin.  Looking at plugin tests, it appears they cover action errors from plugins but not over a transport.

Not knowing the details, it appears to me that plugin action errors over a transport is not covered within the tests.  I also didn't see a timeout error test in the transport test file.

That being said, my mocha tests did pass.  That is, an error was passed into the assert from the action over a transport.  It's just that the error was thrown somewhere (internals.Utils.handle_response?) within the stack as well.

**Comment by MatthewPikar** [comment]
Ok, so going through the code I think the error is no longer thrown as the process is not crashing.  It is merely reported to stdout in the test example.  In my master project the error disappeared altogether after all the upgrades.

But, the error still throws on timeout.  Is there a different way of catching timeout errors (when the server service is not running for example) or should they also be passed through the ACT callback?

**Comment by geek** [comment]
I added a test to demonstrate this behavior.

Do you have a timeout set on the action call that is low enough to make sense for the case, perhaps less than a second?
