### ISSUE TITLE
exception when stopping process

### ISSUE THREAD

**Issue by mihaidma** [senecajs/seneca#266]
While running the seneca-mvp on node `0.10` and `0.12` if I hit Ctrl+C to stop the process getting the following exception:
```
^C
uncaughtException: assertion error
Error: assertion error
    at process.assert (node.js:328:21)
    at process.removeListener (node.js:808:9)
    at seneca/seneca-mvp/node_modules/seneca/seneca.js:896:17
    at seneca/seneca-mvp/node_modules/seneca/node_modules/lodash/index.js:3073:15
    at baseForOwn (seneca/seneca-mvp/node_modules/seneca/node_modules/lodash/index.js:2046:14)
    at seneca/seneca-mvp/node_modules/seneca/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (seneca/seneca-mvp/node_modules/seneca/node_modules/lodash/index.js:3346:13)
    at Seneca.api_close [as close] (seneca/seneca-mvp/node_modules/seneca/seneca.js:894:7)
    at process.handleClose (seneca/seneca-mvp/node_modules/seneca/seneca.js:1730:10)
    at process.g (events.js:180:16)
 ```

Not happening on higher node versions.

**Comment by mcdonnelldean** [comment]
Closed as mvp is being moved to the attic
