### ISSUE TITLE
Any advice how to deal with "Maximum call stack size exceeded." error in context of Seneca?

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca#336]
Here is the call stack

RangeError: Maximum call stack size exceeded
at isObject (/Users/user/projects/proj-seneca/node_modules/lodash/index.js:8736:22)
at baseClone (/Users/user/projects/proj-seneca/node_modules/lodash/index.js:1694:12)
at Function.clone (/Users/user/projects/proj-seneca/node_modules/lodash/index.js:8350:11)
at internals.Utils.resolve_topic (/Users/user/projects/proj-seneca/node_modules/seneca-transport/lib/transport-utils.js:368:20)
at /Users/user/projects/proj-seneca/node_modules/seneca-transport/lib/transport-utils.js:344:22
at Seneca.client.send (/Users/user/projects/proj-seneca/node_modules/seneca-transport/lib/transport-utils.js:301:7)
at Seneca.transport_client (/Users/user/projects/proj-seneca/node_modules/seneca/lib/transport.js:86:25)
at actorModel (/Users/user/projects/proj-seneca/node_modules/seneca-balance-client/balance-client.js:197:27)
at Seneca.<anonymous> (/Users/user/projects/proj-seneca/node_modules/seneca-balance-client/balance-client.js:155:11)
at /Users/user/projects/proj-seneca/node_modules/seneca-transport/lib/transport-utils.js:305:14

**Comment by andriy-zhelvachenko** [comment]
Software does nothing special.

One process (seneca service) publishes events via "act"
3 other processes listen to this event via "add"

This is kind of simulation of fire/sub, but i discovered mulitple issues with that pair.

**Comment by geek** [comment]
@andriy-zhelvachenko can you paste what the value of `pin` is?  Also, what version of seneca are you using?

**Comment by andriy-zhelvachenko** [comment]
I have managed to localize the problem.'

Here is the codebase
https://gist.github.com/andriy-zhelvachenko/669b9e1a9b5518e86092 

I use seneca v.1.0.0
And seneca-mesh v0.4.0

**Comment by andriy-zhelvachenko** [comment]
In order to reproduce the problem follow steps below
1) run "./mesh-base.js"
2) run "./ams.js"
3) run "./bms.js"
4) run "./send-msg.js"
5) observe error stack in the "send-msg" output

**Comment by andriy-zhelvachenko** [comment]
Does it make sense to remark this issue as bug?

**Comment by andriy-zhelvachenko** [comment]
Found the root cause for the problem.

If different mesh processes use semantically same, but alphabetically different pins then it fails with "Max call stack size exceeded" error

i.e. if 2 processes both have
{auto:true, listen:[{pins:['ns:m,what:a,cmd:u'], model:'publish'}]}
this works

if 1 process has
{auto:true, listen:[{pins:['ns:m,what:a,cmd:u'], model:'publish'}]}
and another one has 
{auto:true, listen:[{pins:['ns:m,cmd:u,what:a'], model:'publish'}]}
It fails with the error above!!!

**Comment by andriy-zhelvachenko** [comment]
Submitted bug to mesh repo

**Comment by rjrodger** [comment]
these are the same patterns, so it will loop - order of properties is not significant
