### ISSUE TITLE
"no-current-target" error in client process when when server is killed 

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca#347]
I have the following scenario
- client (act) is constantly (every 15 seconds) polling server (add)
- server and client are located in different processes
- client and server locate each other via mesh

When server is killed, client fails with the error below.
I assume "mesh" or "balance-client" do not get chance to invalidate it's configuration.

Any advice how to handle it?

seneca: no-current-target
       no-current-target       {plugin:{}}     Error: seneca: no-current-target
    at errormaker (/Users/user/projects/myproj/node_modules/eraro/eraro.js:94:15)
    at actorModel (/Users/user/projects/myproj/node_modules/seneca-balance-client/balance-client.js:194:24)
    at Seneca.<anonymous> (/Users/user/projects/myproj/node_modules/seneca-balance-client/balance-client.js:155:11)
    at /Users/user/projects/myproj/node_modules/seneca-transport/lib/transport-utils.js:307:14
    at /Users/user/projects/proj/node_modules/seneca-transport/lib/transport-utils.js:349:14
    at Seneca.client.send (/Users/user/projects/myproj/node_modules/seneca-transport/lib/transport-utils.js:303:7)
    at Seneca.transport_client (/Users/user/projects/myproj/node_modules/seneca/lib/transport.js:88:25)
    at /Users/user/projects/myproj/node_modules/seneca/seneca.js:1123:22
    at act_param_check (/Users/user/projects/myproj/node_modules/seneca/seneca.js:1467:17)
    at Object.execute_action [as fn] (/Users/user/projects/myproj/node_modules/seneca/seneca.js:1067:7)

**Comment by geek** [comment]
@andriy-zhelvachenko this may be a situation where you want to restart the process... another idea is to suppress the message and try to reconnect after a while.

**Comment by andriy-zhelvachenko** [comment]
Any idea how to suppress the error on the client?
I have tried to set seneca.error handler and set fatal$ to false.

But that did not help. 
I.e. method was called but process still got terminated

**Comment by geek** [comment]
One potential option is to change the `seneca.die` function to your own.  It will be called with the `Error` object.

**Comment by mcdonnelldean** [comment]
Related #398

**Comment by mcdonnelldean** [comment]
As above, swapping out seneca.die is probably the best way for now. Error handling is been rethunk in #398 and will have the ability to switch off seneca handling this. Merged with #398
