### ISSUE TITLE
Can a single pattern ignore the gate

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/seneca#376]
Based on this question,

https://github.com/senecajs/q-and-a/issues/3

I was wondering, can you pass a meta value to tell the gate to waiting forever for this particular action call?

**Comment by geek** [comment]
When calling an action, you can specify `gate$: false`

**Comment by ymohammad** [comment]
@geek 
I tried it with gate$: false but it is still giving me the time-out error. Here is the sample code.

> **_server.js_**

```var seneca = require('seneca')();
seneca.listen({ type: 'http', host:'localhost', port:"8787"});

var delay = 34000;
seneca.add({role:'some_role', cmd: 'blokcing_call'}, function (args, done) {
  rabbitmq_consumer(done);
});

function rabbitmq_consumer(done) {
    setTimeout(function(){
        done(null, {status: 'success'}); 
    }, delay);
}
```

> **_client.js_**

```var seneca = require( 'seneca' )().client({type: 'http', host:"localhost", port:"8787"});

seneca.act({role:'some_role', cmd: 'blokcing_call', gate$: false}, function(err, resp) { 
    if(err) {
        console.log(err);
    }
    console.log('Client Blocking call registed.', resp); 
});
```

At when executing the client.js, it is still giving me time-out error.

**Comment by geek** [comment]
You can override the timeout for the seneca client instance when you create it (https://github.com/senecajs/seneca/blob/master/seneca.js#L54) The default is `22222` and your test has a 30s delay, this is why the error occurs.

**Comment by ymohammad** [comment]
@geek Thanks for the reply. But after overriding the timeout value, I am still facing the same error. In the actual implementation, we have few microservices which take more than the default 22 seconds (happen sometimes not always). So, the client is just showing timeout. Is there any way I can make my client to wait till the server  completes its execution and give me the result.

I have tried the below code.

server.js

```
var seneca = require('seneca')({ timeout: 75000});
seneca.listen({ type: 'http', host:'localhost', port:"8787"});

var delay = 30000;
seneca.add({role:'some_role', cmd: 'blokcing_call'}, function (args, done) {
  rabbitmq_consumer(done);
  
});

function rabbitmq_consumer(done) {
    setTimeout(function(){
        console.log("Calling done now..");
        done(null, {status: 'success'}); 
    }, delay);
    console.log("Set timeout is already called..");
}
```

client.js

```
var seneca = require( 'seneca' )({ timeout: 75000}).client({type: 'http', host:"localhost", port:"8787"});

seneca.act({role:'some_role', cmd: 'blokcing_call'}, function(err, resp) { 
    if(err) {
        console.log(err);
    } else {
        console.log('Client Blocking call registed.', resp); 
    }
});
```

Output

```
["client","invalid_origin",{"type":"web","host":"localhost","port":"8787","pg":"","id":"host:localhost,pg:,port:8787,type:http","role":"transport","hook":"client","plugin$":{"name":"client$"},"fatal$":true,"meta$":{"mi":"h7ekzwemr
qu9","tx":"leqpu1wwako7","id":"h7ekzwemrqu9/leqpu1wwako7","pattern":"hook:client,role:transport,type:web","action":"(jmy46dcwr34x)","plugin_name":"transport","plugin_tag":"-","prior":{"chain":[],"entry":true,"depth":0},"start":148
9806751541,"sync":true},"tx$":"leqpu1wwako7","path":"/act","protocol":"http","timeout":5555,"max_listen_attempts":11,"attempt_delay":222,"serverOptions":{}},{"kind":"res","res":null,"error":{"isBoom":true,"isServer":true,"output":
{"statusCode":504,"payload":{"statusCode":504,"error":"Gateway Time-out","message":"Client request timeout"},"headers":{}}},"sync":true,"time":{"client_recv":1489806757114}}]
{"notice":"seneca: Action  failed: [TIMEOUT].","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action  failed: [TIMEOUT].","details":{"message":"[TIMEOUT]","p
attern":"","instance":"Seneca/rn3ymvjwzuw2/1489806751244/23264/3.3.0/-","orig$":{},"message$":"[TIMEOUT]","plugin":{}},"callpoint":"at Object.act_tm [as ontm] (C:\\Sufiyan_Files\\GitSourceCode\\full_purging_code\\mes_gaia\\applica
tions\\packaging\\node_modules\\seneca\\seneca.js:1045:46)"},"actid":"677vdfknbybs/y9wshm5dlpto","msg":{"role":"some_role","cmd":"blokcing_call","meta$":{"mi":"677vdfknbybs","tx":"y9wshm5dlpto","id":"677vdfknbybs/y9wshm5dlpto","pa
ttern":"","action":"(ispuzgmwerrh)","plugin_name":"client$","plugin_tag":"-","prior":{"chain":[],"entry":true,"depth":0},"start":1489806751507,"sync":true},"plugin$":{"name":"client$","tag":"-"},"tx$":"y9wshm5dlpto"},"entry":true,
"prior":[],"meta":{"plugin_name":"client$","plugin_tag":"-","plugin_fullname":"client$","raw":{"client$":true,"internal$":{"catchall":true}},"sub":false,"client":true,"args":{},"rules":{},"id":"(ispuzgmwerrh)","pattern":"","msgcan
on":{},"priorpath":""},"client":true,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":75123,"level":"error","when":1489806826645}
{ Error: [TIMEOUT]
    at Object.act_tm [as ontm] (C:\Sufiyan_Files\GitSourceCode\full_purging_code\mes_gaia\applications\packaging\node_modules\seneca\seneca.js:1045:46)
    at Timeout.timeout_check [as _onTimeout] (C:\Sufiyan_Files\GitSourceCode\full_purging_code\mes_gaia\applications\packaging\node_modules\gate-executor\gate-executor.js:216:16)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  eraro: true,
  orig:
   Error: [TIMEOUT]
       at Object.act_tm [as ontm] (C:\Sufiyan_Files\GitSourceCode\full_purging_code\mes_gaia\applications\packaging\node_modules\seneca\seneca.js:1045:46)
       at Timeout.timeout_check [as _onTimeout] (C:\Sufiyan_Files\GitSourceCode\full_purging_code\mes_gaia\applications\packaging\node_modules\gate-executor\gate-executor.js:216:16)
       at ontimeout (timers.js:365:14)
       at tryOnTimeout (timers.js:237:5)
       at Timer.listOnTimeout (timers.js:207:5),
  code: 'act_execute',
  seneca: true,
  package: 'seneca',
  msg: 'seneca: Action  failed: [TIMEOUT].',
  details:
   { message: '[TIMEOUT]',
     pattern: '',
     fn: { [Function: transport_client] id: 'host:localhost,pg:,port:8787,type:http' },
     cb: [Function],
     instance: 'Seneca/rn3ymvjwzuw2/1489806751244/23264/3.3.0/-',
     'orig$':
      Error: [TIMEOUT]
          at Object.act_tm [as ontm] (C:\Sufiyan_Files\GitSourceCode\full_purging_code\mes_gaia\applications\packaging\node_modules\seneca\seneca.js:1045:46)
          at Timeout.timeout_check [as _onTimeout] (C:\Sufiyan_Files\GitSourceCode\full_purging_code\mes_gaia\applications\packaging\node_modules\gate-executor\gate-executor.js:216:16)
          at ontimeout (timers.js:365:14)
          at tryOnTimeout (timers.js:237:5)
          at Timer.listOnTimeout (timers.js:207:5),
     'message$': '[TIMEOUT]',
     plugin: {} },
  callpoint: 'at Object.act_tm [as ontm] (C:\\Sufiyan_Files\\GitSourceCode\\full_purging_code\\mes_gaia\\applications\\packaging\\node_modules\\seneca\\seneca.js:1045:46)' }
{"kind":"notice","notice":"hello seneca rn3ymvjwzuw2/1489806751244/23264/3.3.0/-","level":"info","when":1489806826656}
```

**Comment by geek** [comment]
@rjrodger or @mcdonnelldean, any ideas on the timeout issue?
