### ISSUE TITLE
Seneca ignores errors when a result is present in a reply message.

### ISSUE THREAD

**Issue by ssmereka** [senecajs/seneca#462]
When returning both an error and a result in a seneca reply message, seneca is ignoring the error.  

```javascript
var seneca = require('seneca')()

seneca.add('role:my_role,cmd:my_cmd', (msg, reply) => {
  reply(new Error("An error occurred"), {data: "but here is some data anyways."})
})

seneca.act({role: 'my_role', cmd: 'my_cmd'}, function (err, result) {
  console.log(err);     // null
  console.log(result);  // {data: "but here is some data anyways."}
})
```

**Comment by indr** [comment]
It works for me. When I run this script:
```js
const seneca = require('seneca')()

seneca.add('role:my_role,cmd:my_cmd', (msg, reply) => {
  reply(new Error("An error occurred"), {data: "but here is some data anyways."})
})

seneca.act({role: 'my_role', cmd: 'my_cmd'}, function (err, result) {
  console.log('err == null:', err == null);
  console.log(result);  // {data: "but here is some data anyways."}
  console.log('seneca: ', this.version);
  console.log('node:   ', process.version);
})
```

I get
```bash
$ node app.js 
2016-08-04T08:54:30.271Z 5jrc2ativ5eg/1470300870234/3885/2.1.0/- INFO	hello	Seneca/5jrc2ativ5eg/1470300870234/3885/2.1.0/-
2016-08-04T08:54:30.537Z 5jrc2ativ5eg/1470300870234/3885/2.1.0/- ERROR	act	root$       	OUT	ektpzc33njh4/ujzg2z8pjpfy	-	47	{role:my_role,cmd:my_cmd}	ENTRY	(80x5ie3v7kjn)	-seneca: Action cmd:my_cmd,role:my_role failed: An error occurred.	act_execute	{id:ektpzc33njh4/ujzg2z8pjpfy,gate:false,ungate:false,desc:null,time:{start:1470300870530,end:1470300870531},me	Error: An error occurred
    at Seneca.seneca.add (/home/reto/Projects/senecajs/issues/462/app.js:4:9)
    at Array.done (/home/reto/Projects/senecajs/issues/462/node_modules/seneca/seneca.js:1193:22)
    at validate_action_message (/home/reto/Projects/senecajs/issues/462/node_modules/seneca/seneca.js:1545:19)
    at Object.execute_action [as fn] (/home/reto/Projects/senecajs/issues/462/node_modules/seneca/seneca.js:1126:7)
    at Immediate.<anonymous> (/home/reto/Projects/senecajs/issues/462/node_modules/gate-executor/gate-executor.js:136:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)	
err == null: false
{ data: 'but here is some data anyways.' }
seneca:  2.1.0
node:    v6.3.1
```
`err == null: false` :+1: 

What version of seneca and node are you using?

**Comment by ssmereka** [comment]
I am using node ```v6.2.0``` and seneca ```v2.1.0```.  It occurs when using a client and server.  Sorry, this is a better example:

# Client.js
```javascript
var seneca = require('seneca')();

seneca.act({role: 'my_role', cmd: 'my_cmd'}, function (err, result) {
  console.log(err);     // null
  console.log(result);  // {data: "but here is some data anyways."}
  console.log('Seneca Version: %s', this.version);
  console.log('Node Version: %s', process.version);
})

seneca.client({ type: 'http', pin: 'role:my_role' });
``` 

# Server.js
```javascript
var seneca = require('seneca')();

seneca.add('role:my_role,cmd:my_cmd', (msg, reply) => {
  reply(new Error("An error occurred"), {data: "but here is some data anyways."})
})

seneca.listen({ type: 'http', pin: 'role:my_role' });
```

# Server Output

```
$ node server.js
2016-08-04T13:25:05.504Z v1dzg98wk79p/1470317105486/5875/- INFO	hello	Seneca/2.1.0/v1dzg98wk79p/1470317105486/5875/-
2016-08-04T13:25:05.788Z v1dzg98wk79p/1470317105486/5875/- INFO	listen	{type:http,pin:role:my_role}
2016-08-04T13:25:10.843Z v1dzg98wk79p/1470317105486/5875/- ERROR	act	root$       	OUT		cmd:my_cmd,role:my_role	4	{role:my_role,cmd:my_cmd}	ENTRY	(758wwntmbdie)	-	seneca: Action cmd:my_cmd,role:my_role failed: An error occurred.	act_execute	{id:42r2qly8uhnh/b4yoq8sf3y2s,gate:false,ungate:true,desc:null,time:{start:1470317110838,end:1470317110839},mes	Error: An error occurred
    at Seneca.seneca.add (/Users/ssmereka/Documents/Scott/senecajs 462/server.js:4:9)
    at Array.done (/Users/ssmereka/Documents/Scott/senecajs 462/node_modules/seneca/seneca.js:1172:22)
    at validate_action_message (/Users/ssmereka/Documents/Scott/senecajs 462/node_modules/seneca/seneca.js:1504:19)
    at Object.execute_action [as fn] (/Users/ssmereka/Documents/Scott/senecajs 462/node_modules/seneca/seneca.js:1115:7)
    at Immediate._onImmediate (/Users/ssmereka/Documents/Scott/senecajs 462/node_modules/gate-executor/gate-executor.js:136:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

# Client Output
```
$ node client.js
2016-08-04T13:25:10.462Z sdttw6ak6vow/1470317110443/5879/- INFO	hello	Seneca/2.1.0/sdttw6ak6vow/1470317110443/5879/-
2016-08-04T13:25:10.749Z sdttw6ak6vow/1470317110443/5879/- INFO	client	{type:http,pin:role:my_role}
null
{ data: 'but here is some data anyways.' }
Seneca Version: 2.1.0
Node Version: v6.2.0
Scotts-MBP:senecajs 462 ssmereka$
```

> Notice that the error is ```null``` in this scenario.

**Comment by indr** [comment]
Yeah, can reproduce. It's interesting because it works if I
 - use `tcp`
 - or wrap either the `seneca.client(...)` or `seneca.act(...)` in `seneca.ready(...)`

**Comment by rjrodger** [comment]
Errors should take precedence.
