### ISSUE TITLE
Response with statusCode 201 throws error

### ISSUE THREAD

**Issue by amitava82** [senecajs/seneca#495]
This is really weird. I have a very simple seneca client and server setup from the tutorial. Only difference is that in the callback I have a `statusCode` property like so:
```
  function sum(msg, respond) {
    var out = { answer: msg.left + msg.right }
    log('sum '+msg.left+'+'+msg.right+'='+out.answer+'\n')
    respond(null, {
      statusCode: 201,
      result: out
    })
  }
```
If I set the `statusCode` to `200` or remove the property it works just fine. Even with just `status: 201` it works fine.  With `statusCode: 201` client throws error.

Error:
```
2016-08-17T16:50:51.537Z l6bqeavwrynj/1471452651508/24847/- INFO	hello	Seneca/1.4.0/l6bqeavwrynj/1471452651508/24847/-
2016-08-17T16:50:51.978Z l6bqeavwrynj/1471452651508/24847/- INFO	client
2016-08-17T16:50:52.169Z l6bqeavwrynj/1471452651508/24847/- ERROR	act	client$       	OUT		-	172	{role:math,cmd:sum,left:1,right:2}	ENTRY	(ccs0hma03ip2)	-	seneca: Action  failed: .	act_execute	{id:j8da5w0vokbj/mc20vge2uj6g,gate:false,ungate:false,desc:null,time:{start:1471452652116,end:1471452652162},me	Error
    at internals.Utils.handle_response (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:70:11)
    at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/http.js:146:25
    at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:472:20
    at finish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:326:16)
    at wrapped (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/node_modules/hoek/lib/index.js:866:20)
    at onReaderFinish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:363:16)
    at g (events.js:286:16)
    at emitNone (events.js:91:20)
    at emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:488:14)
{ Error
    at internals.Utils.handle_response (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:70:11)
    at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/http.js:146:25
    at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:472:20
    at finish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:326:16)
    at wrapped (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/node_modules/hoek/lib/index.js:866:20)
    at onReaderFinish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:363:16)
    at g (events.js:286:16)
    at emitNone (events.js:91:20)
    at emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:488:14)
  statusCode: 201,
  result: { answer: 3 },
  eraro: true,
  orig:
   { Error
       at internals.Utils.handle_response (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:70:11)
       at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/http.js:146:25
       at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:472:20
       at finish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:326:16)
       at wrapped (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/node_modules/hoek/lib/index.js:866:20)
       at onReaderFinish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:363:16)
       at g (events.js:286:16)
       at emitNone (events.js:91:20)
       at emit (events.js:185:7)
       at finishMaybe (_stream_writable.js:488:14)
     statusCode: 201,
     result: { answer: 3 },
     eraro: true,
     orig:
      { Error
          at internals.Utils.handle_response (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:70:11)
          at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/http.js:146:25
          at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:472:20
          at finish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:326:16)
          at wrapped (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/node_modules/hoek/lib/index.js:866:20)
          at onReaderFinish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:363:16)
          at g (events.js:286:16)
          at emitNone (events.js:91:20)
          at emit (events.js:185:7)
          at finishMaybe (_stream_writable.js:488:14) statusCode: 201, result: [Object] },
     code: 'action-error',
     'gate-executor': true,
     package: 'gate-executor',
     msg: 'gate-executor: ',
     details:
      { id: 'j8da5w0vokbj/mc20vge2uj6g',
        gate: false,
        ungate: false,
        desc: undefined,
        cb: [Function: act_done],
        fn: [Function: execute_action],
        time: [Object],
        'orig$': [Object],
        'message$': '' },
     callpoint: 'at internals.Utils.handle_response (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:70:11)' },
  code: 'act_execute',
  'gate-executor': true,
  package: 'seneca',
  msg: 'seneca: Action  failed: .',
  details:
   { id: 'j8da5w0vokbj/mc20vge2uj6g',
     gate: false,
     ungate: false,
     desc: undefined,
     cb: [Function: bound ],
     fn: { [Function: transport_client] id: 'pg:' },
     time: { start: 1471452652116, end: 1471452652162 },
     'orig$':
      { Error
          at internals.Utils.handle_response (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:70:11)
          at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/http.js:146:25
          at /Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:472:20
          at finish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:326:16)
          at wrapped (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/node_modules/hoek/lib/index.js:866:20)
          at onReaderFinish (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:363:16)
          at g (events.js:286:16)
          at emitNone (events.js:91:20)
          at emit (events.js:185:7)
          at finishMaybe (_stream_writable.js:488:14) statusCode: 201, result: [Object] },
     'message$': '',
     message: '',
     pattern: '',
     instance: 'Seneca/1.4.0/l6bqeavwrynj/1471452651508/24847/-',
     plugin: {} },
  callpoint: 'at internals.Utils.handle_response (/Users/amitava/senecajs-tutorial/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:70:11)',
  seneca: true } null { id: 'j8da5w0vokbj/mc20vge2uj6g',
  accept: '6t8o5s6koiyv/1471452648011/24843/-',
  track: undefined,
  time:
   { client_sent: '0',
     listen_recv: '0',
     listen_sent: '0',
     client_recv: 1471452652161 } }
```

**Comment by mcdonnelldean** [comment]
@amitava82 Hey, which tutorial specifically is this from?

**Comment by amitava82** [comment]
@mcdonnelldean I don't think it's specific to any tutorial. Here is simplest code to reproduce:

```
//server.js
var seneca = require('seneca')()
	.use(require('./math'),{logfile:'./math.log'})
	
	seneca.listen();
``` 
```
//math.js
module.exports = math;

function math(options) {

  this.add('role:math,cmd:sum', sum);

  function sum(msg, respond) {
    var out = { answer: msg.left + msg.right };
    respond(null, {
      statusCode: 201,
      result: out
    })
  }
}
```
```
//client.js
require('seneca')()
  .client()
  .act('role:math,cmd:sum,left:1,right:2', function(e, r){
  	console.log(e,r);
  })
```

**Comment by mcdonnelldean** [comment]
I bet it is to do with our http router for the http transport. I'll have a look at this during the week.

**Comment by mcdonnelldean** [comment]
@amitava82 I've moved this to https://github.com/senecajs/seneca-transport/issues/119 so it doesn't get lost when we are looking at transport.

Looks like a bug for sure. Thanks for the report.
