### ISSUE TITLE
 seneca: No matching action pattern found

### ISSUE THREAD

**Issue by guptakvgaurav** [senecajs/seneca#524]
I am trying to learn build micro-services with seneca, but getting below mentioned error.

Message: seneca: No matching action pattern found for { use:    { prefix: '/api',     pin: 'role:api,path:*',     map: { catalog: [Object] } },  role: 'web' }, and no default result provided (using a default$ property).

Code: `act_not_found`

Details: `{ args: '{ use:    { prefix: \'/api\',     pin: \'role:api,path:*\',     map: { catalog: [Object] } },  role: \'web\' }' }`

Stack: 
```
    at Object.errormaker [as error] (/home/ttnd/workspace/labs/bbtb/starter/node_modules/eraro/eraro.js:94:15)
    at executable_action (/home/ttnd/workspace/labs/bbtb/starter/node_modules/seneca/seneca.js:1155:23)
    at execute_action (/home/ttnd/workspace/labs/bbtb/starter/node_modules/seneca/seneca.js:875:12)
    at Object.execspec.fn [as orig_fn] (/home/ttnd/workspace/labs/bbtb/starter/node_modules/seneca/seneca.js:1084:11)
    at Object.timeout_fn [as fn] (/home/ttnd/workspace/labs/bbtb/starter/node_modules/gate-executor/gate-executor.js:194:12)
    at next (/home/ttnd/workspace/labs/bbtb/starter/node_modules/gate-executor/gate-executor.js:126:14)
    at process (/home/ttnd/workspace/labs/bbtb/starter/node_modules/gate-executor/gate-executor.js:175:12)
    at Immediate._onImmediate (/home/ttnd/workspace/labs/bbtb/starter/node_modules/gate-executor/gate-executor.js:258:7)

```

**Web server code**
```
var` seneca = require( 'seneca' ),
	senecaOptions = {
		default_plugins: {
			'web': false
		}
	},
	express = require( 'express' ),
	app = express(),
	senecaWeb = require('seneca-web');

seneca(senecaOptions)
	.use( './api' )
	.client({port:3001, pin:'role:catalog'});


app.use( require('body-parser').json() )
   .use( senecaWeb )	// plugin - seneca-web ; used for express routes to seneca actions mapping
   .listen(3000)

```

**api.js**

```
var apiOptions = {
	use: {
		prefix: '/api',	// route will start with /api
		pin: 'role:api,path:*',
		map: {
			catalog: { GET: true, suffix: '/:operation'}	
		}
	}
},
	valid_categories = {  "electronics": "electronics", "fashion": "fashion" },
	valid_ops = { "list": "list" };


module.exports = function api(options) {
	this.add('role:api,path:catalog', function (msg, respond) {
		console.log('Catalog called');
		this.act('role:catalog', {
			cmd: valid_ops[msg.operation]
		});
	});

	// init:api -- called upon initialization of this microservice
	this.add('init:api', function (msg, respond) {
		this.act('role:web', apiOptions, respond);
	});
};

```

**MicroService1 (Catalog service ) code**
```
var seneca = require('seneca');
module.exports = function Catalog() {	// should provide name of function here. used by seneca for while logging 

	
	this.add('role:catalog,cmd:list', function (msg, done){
		console.log("electronics");
		done(null, {status: "success"});
	});

	this.add('role:catalog,cmd:list', function (msg, done){
		console.log('fashion');
		done(null, {status: "success"});
	});

	// this.wrap('role:catalog,category:electronics', function (msg, respond) {
	// 	console.log('Wrap electronics --> %s --> %s', msg.category, msg.cmd);
	// 	this.prior(msg, respond);
	// });

	this.wrap('role:catalog', function (msg, respond) {
		console.log('Wrap --> %s --> %s', msg.cmd);
		this.prior(msg, respond);
	});

}

```
**server.js ( belongs to catalog service )**

```
var seneca = require('seneca')();
var CatalogMicroService = require('./catalog');

seneca
	.use(CatalogMicroService)	// load u-service from here.
	// .act('role:catalog,category:home&decor,cmd:list', console.log)	// for testing purpose: send jsonic message
	// .act('role:catalog,category:fashion,cmd:list', console.log)	// for testing purpose: send jsonic message
	.listen({pin:'role:catalog', port:3001});	// listen to all messages coming through `tcp` protocol and whose `pin` is matching to `role:catalog`

```

I am not able to track and fix the root cause for the error.

**Comment by dgonzalez** [comment]
This seems more a seneca-web problem: https://github.com/senecajs/seneca-web

Can you please report the issue in there?

Thanks!

**Comment by guptakvgaurav** [comment]
@dgonzalez Yup !! I came across that issue ( [https://github.com/senecajs/seneca-web/issues/78](url) ) .

**Comment by dgonzalez** [comment]
We are working right now on it. It will be ready soon. Meanwhile, you can have a look to the PR: https://github.com/senecajs/seneca-web/pull/79

There are few examples in there. Ping us again if you need any help.

**Comment by mcdonnelldean** [comment]
@guptakvgaurav I'm going to close. We are a couple of days out from relaunching seneca web based on the PR above. Once released I will note here.
