### ISSUE TITLE
command option --seneca.log.all crash

### ISSUE THREAD

**Issue by blanchma** [senecajs/seneca#540]
I'm using. I was trying to log every request I receive in one microservice and try the option --seneca.log.all with seneca v3.0.0. 

node app.js --seneca.log.all

/Users/blanchma/workspace/changes/node_modules/seneca/lib/optioner.js:81
      Legacy.parse_command_line(argv.seneca.log,
             ^

TypeError: Legacy.parse_command_line is not a function
    at module.exports (/Users/blanchma/workspace/changes/node_modules/seneca/lib/optioner.js:81:14)
    at make_seneca (/Users/blanchma/workspace/changes/node_modules/seneca/seneca.js:253:23)
    at init (/Users/blanchma/workspace/changes/node_modules/seneca/seneca.js:184:16)
    at Object.<anonymous> (/Users/blanchma/workspace/changes/seneca.js:1:14)
    at Module._compile (module.js:409:26)
    at loader (/Users/blanchma/workspace/changes/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/blanchma/workspace/changes/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by mihaidma** [comment]
command line arguments are not implemented in seneca 3.0.0 but we added support for them in 3.1.0 (will be published probably this week). The functionality is merged to master.

For the moment to log you have to use seneca options, see the docs for more details: http://senecajs.org/api/#log-level-entry-

Please close the issue if this answer clarified the problem.

**Comment by blanchma** [comment]
@mihaidma Okey but have in mind that if I do:
var seneca = Seneca({
  log: { level: 'warn+' }
})

The built-in logs stop logging anything. It become silent.

**Comment by mihaidma** [comment]
Could you put this snippet into a file:

```
var seneca = Seneca({
  log: { level: 'warn+' }
})
seneca.log.debug('debug log level')
seneca.log.info('info log level')
seneca.log.warn('warn log level')
seneca.log.error('error log level')
seneca.log.fatal('fatal log level')
```
and tell me if it works? Also what is your OS and Node version?

**Comment by mcdonnelldean** [comment]
[3.1](https://github.com/senecajs/seneca/releases/tag/v3.1.0) is now out and should correct this
