### ISSUE TITLE
Error handling across plugins

### ISSUE THREAD

**Issue by ygist** [senecajs/seneca#580]
I'm confused about how error handling works across plugins, not sure if this is a bug or i'm not using seneca correctly:
```javascript
var seneca = require('seneca')();

var plugin1 = function plugin1() {
  var seneca = this;
  seneca.add({role:'plugin1', cmd: 'resolve'}, function (args, done) {
    seneca.act({role:'plugin2', cmd: 'reject'}, function (err, reply) {
      console.log('should reach here @2');
      done(err, reply);
    });
  });
}

var plugin2 = function plugin2() {
  var seneca = this;
  seneca.add({role:'plugin2', cmd: 'reject'}, function (args, done) {
    done(new Error("rejected"));
  });
}

seneca.use(plugin1);
seneca.use(plugin2);


seneca.act({role:'plugin1', cmd: 'resolve'}, function (err, reply) {
  console.log('should reach here @1');
})
```
I ran the above code with node 6.2.0 and seneca 3.2.2 but the program never reaches the console.logs:
```
{"kind":"notice","notice":"hello seneca qfdifnlg685w/1478043631558/23201/3.2.2/-","level":"info","when":1478043631622}
(node:23201) DeprecationWarning: 'root' is deprecated, use 'global'
{"notice":"seneca: Action cmd:reject,role:plugin2 failed: rejected.","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:reject,role:plugin2 failed: rejected.","details":{"message":"rejected","pattern":"cmd:reject,role:plugin2","instance":"Seneca/qfdifnlg685w/1478043631558/23201/3.2.2/-","orig$":{},"message$":"rejected","plugin":{}},"callpoint":"at Seneca.<anonymous> (/Users/ye.li/tmp/seneca/pluginErrors.js:16:10)"},"actid":"yr3keqniaqrj/v6wo0mzqnvpm","msg":{"role":"plugin2","cmd":"reject","plugin$":{"name":"plugin1"},"fatal$":true,"meta$":{"id":"6cph8ietjwtp/tz04j05oepu9","tx":"tz04j05oepu9","pattern":"cmd:reject,role:plugin2","action":"(7dziqyoppjqq)","plugin_name":"plugin2","plugin_tag":"-","prior":{"chain":[],"entry":true,"depth":0},"start":1478043631775,"sync":true},"tx$":"tz04j05oepu9"},"entry":true,"prior":[],"meta":{"plugin_name":"plugin2","plugin_tag":"-","plugin_fullname":"plugin2","raw":{"role":"plugin2","cmd":"reject"},"sub":false,"client":false,"args":{"role":"plugin2","cmd":"reject"},"rules":{},"id":"(7dziqyoppjqq)","pattern":"cmd:reject,role:plugin2","msgcanon":{"cmd":"reject","role":"plugin2"},"priorpath":""},"client":false,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":0,"level":"error","plugin_name":"plugin1","pattern":"name:plugin1,plugin:define,role:seneca,seq:2,tag:undefined","when":1478043631781}
[]


Seneca Fatal Error
==================

Message: seneca: Action cmd:reject,role:plugin2 failed: rejected.

Code: act_execute

Details: { message: 'rejected',
  pattern: 'cmd:reject,role:plugin2',
  fn: [Function],
  cb: [Function],
  instance: 'Seneca/qfdifnlg685w/1478043631558/23201/3.2.2/-',
  'orig$':
   Error: rejected
       at Seneca.<anonymous> (/Users/ye.li/tmp/seneca/pluginErrors.js:16:10)
       at execute_action (/Users/ye.li/tmp/seneca/node_modules/seneca/seneca.js:1060:20)
       at Object.act_fn [as fn] (/Users/ye.li/tmp/seneca/node_modules/seneca/seneca.js:1013:11)
       at Immediate.processor [as _onImmediate] (/Users/ye.li/tmp/seneca/node_modules/gate-executor/gate-executor.js:136:14)
       at tryOnImmediate (timers.js:543:15)
       at processImmediate [as _immediateCallback] (timers.js:523:5),
  'message$': 'rejected',
  plugin: {} }

Stack:
    at Seneca.<anonymous> (/Users/ye.li/tmp/seneca/pluginErrors.js:16:10)
    at execute_action (/Users/ye.li/tmp/senec%
```

However, converting the same program to use promises reached the console.logs:
```javascript
var seneca = require('seneca')();
var bluebird = require('bluebird');

var actAsync = bluebird.promisify(seneca.act, {context: seneca});

var plugin1 = function plugin1() {
  var seneca = this;
  seneca.add({role:'plugin1', cmd: 'resolve'}, function (args, done) {
    actAsync({role:'plugin2', cmd: 'reject'})
      .then(function (reply) {
        done(null, {message: "plugin1 reply"});
      })
      .catch(function(err) {
        console.log('should reach here @2');
        done(err);
      });
  });
}

var plugin2 = function plugin2() {
  var seneca = this;
  seneca.add({role:'plugin2', cmd: 'reject'}, function (args, done) {
    done(new Error("rejected"));
  });
}

seneca.use(plugin1);
seneca.use(plugin2);


actAsync({role:'plugin1', cmd: 'resolve'})
  .then(function (reply) {
    console.log('shouldn\'t be here @3');
  })
  .catch(function (err) {
    console.log('should reach here @1');
  });
```
```
{"kind":"notice","notice":"hello seneca wnc8beseg6f0/1478043061676/23012/3.2.2/-","level":"info","when":1478043061743}
(node:23012) DeprecationWarning: 'root' is deprecated, use 'global'
{"notice":"seneca: Action cmd:reject,role:plugin2 failed: rejected.","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:reject,role:plugin2 failed: rejected.","details":{"message":"rejected","pattern":"cmd:reject,role:plugin2","instance":"Seneca/wnc8beseg6f0/1478043061676/23012/3.2.2/-","orig$":{},"message$":"rejected","plugin":{}},"callpoint":"at Seneca.<anonymous> (/Users/ye.li/tmp/seneca/pluginErrorsPromise.js:23:10)"},"actid":"zbk07vv1vnsq/aeij7on1okhl","msg":{"role":"plugin2","cmd":"reject","meta$":{"id":"zbk07vv1vnsq/aeij7on1okhl","tx":"aeij7on1okhl","pattern":"cmd:reject,role:plugin2","action":"(fqivsf2h5k7z)","plugin_name":"plugin2","plugin_tag":"-","prior":{"chain":[],"entry":true,"depth":0},"start":1478043061935,"sync":true},"plugin$":{"name":"plugin2","tag":"-"},"tx$":"aeij7on1okhl"},"entry":true,"prior":[],"meta":{"plugin_name":"plugin2","plugin_tag":"-","plugin_fullname":"plugin2","raw":{"role":"plugin2","cmd":"reject"},"sub":false,"client":false,"args":{"role":"plugin2","cmd":"reject"},"rules":{},"id":"(fqivsf2h5k7z)","pattern":"cmd:reject,role:plugin2","msgcanon":{"cmd":"reject","role":"plugin2"},"priorpath":""},"client":false,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":0,"level":"error","when":1478043061940}
should reach here @2
{"notice":"seneca: Action cmd:reject,role:plugin2 failed: rejected.","code":"act_execute","err":{"cause":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:reject,role:plugin2 failed: rejected.","details":{"message":"rejected","pattern":"cmd:reject,role:plugin2","instance":"Seneca/wnc8beseg6f0/1478043061676/23012/3.2.2/-","orig$":{},"message$":"rejected","plugin":{}},"callpoint":"at Seneca.<anonymous> (/Users/ye.li/tmp/seneca/pluginErrorsPromise.js:23:10)"},"isOperational":true,"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:reject,role:plugin2 failed: rejected.","details":{"message":"rejected","pattern":"cmd:reject,role:plugin2","instance":"Seneca/wnc8beseg6f0/1478043061676/23012/3.2.2/-","orig$":{},"message$":"rejected","plugin":{}},"callpoint":"at Seneca.<anonymous> (/Users/ye.li/tmp/seneca/pluginErrorsPromise.js:23:10)"},"actid":"lohlwiepnub6/0jp29d7fds2u","msg":{"role":"plugin1","cmd":"resolve","meta$":{"id":"lohlwiepnub6/0jp29d7fds2u","tx":"0jp29d7fds2u","pattern":"cmd:resolve,role:plugin1","action":"(s8eelfe0hxpi)","plugin_name":"plugin1","plugin_tag":"-","prior":{"chain":[],"entry":true,"depth":0},"start":1478043061906,"sync":true},"plugin$":{"name":"plugin1","tag":"-"},"tx$":"0jp29d7fds2u"},"entry":true,"prior":[],"meta":{"plugin_name":"plugin1","plugin_tag":"-","plugin_fullname":"plugin1","raw":{"role":"plugin1","cmd":"resolve"},"sub":false,"client":false,"args":{"role":"plugin1","cmd":"resolve"},"rules":{},"id":"(s8eelfe0hxpi)","pattern":"cmd:resolve,role:plugin1","msgcanon":{"cmd":"resolve","role":"plugin1"},"priorpath":""},"client":false,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":36,"level":"error","when":1478043061943}
should reach here @1
```
there also doesn't seem to be a problem when there are no plugins
```javascript
var seneca = require('seneca')();

seneca.add({role:'plugin1', cmd: 'resolve'}, function (args, done) {
  seneca.act({role:'plugin1', cmd: 'reject'}, function (err, reply) {
    console.log('should reach here @2');
    done(err, reply);
  });
});

seneca.add({role:'plugin1', cmd: 'reject'}, function (args, done) {
  done(new Error("rejected"));
});

seneca.act({role:'plugin1', cmd: 'resolve'}, function (err, reply) {
  console.log('should reach here @1');
})
```
```
{"kind":"notice","notice":"hello seneca ck7txr9lr6g9/1478044869202/23639/3.2.2/-","level":"info","when":1478044869269}
(node:23639) DeprecationWarning: 'root' is deprecated, use 'global'
{"notice":"seneca: Action cmd:reject,role:plugin1 failed: rejected.","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:reject,role:plugin1 failed: rejected.","details":{"message":"rejected","pattern":"cmd:reject,role:plugin1","instance":"Seneca/ck7txr9lr6g9/1478044869202/23639/3.2.2/-","orig$":{},"message$":"rejected","plugin":{}},"callpoint":"at Seneca.<anonymous> (/Users/ye.li/tmp/seneca/errorHanldingNoPlugin.js:11:8)"},"actid":"dd10hqukyglx/0she0mda9i79","msg":{"role":"plugin1","cmd":"reject","meta$":{"id":"dd10hqukyglx/0she0mda9i79","tx":"0she0mda9i79","pattern":"cmd:reject,role:plugin1","action":"(m4ocedhtrmhu)","plugin_name":"root$","prior":{"chain":[],"entry":true,"depth":0},"start":1478044869412,"sync":true},"plugin$":{"name":"root$"},"tx$":"0she0mda9i79"},"entry":true,"prior":[],"meta":{"raw":{"role":"plugin1","cmd":"reject"},"plugin_name":"root$","plugin_fullname":"root$","sub":false,"client":false,"args":{"role":"plugin1","cmd":"reject"},"rules":{},"id":"(m4ocedhtrmhu)","pattern":"cmd:reject,role:plugin1","msgcanon":{"cmd":"reject","role":"plugin1"},"priorpath":""},"client":false,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":0,"level":"error","when":1478044869420}
should reach here @2
{"notice":"seneca: Action cmd:reject,role:plugin1 failed: rejected.","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:reject,role:plugin1 failed: rejected.","details":{"message":"rejected","pattern":"cmd:reject,role:plugin1","instance":"Seneca/ck7txr9lr6g9/1478044869202/23639/3.2.2/-","orig$":{},"message$":"rejected","plugin":{}},"callpoint":"at Seneca.<anonymous> (/Users/ye.li/tmp/seneca/errorHanldingNoPlugin.js:11:8)"},"actid":"q5h8xwevwcne/grq6kj1wss2h","msg":{"role":"plugin1","cmd":"resolve","meta$":{"id":"q5h8xwevwcne/grq6kj1wss2h","tx":"grq6kj1wss2h","pattern":"cmd:resolve,role:plugin1","action":"(fr80qezan8wm)","plugin_name":"root$","prior":{"chain":[],"entry":true,"depth":0},"start":1478044869392,"sync":true},"plugin$":{"name":"root$"},"tx$":"grq6kj1wss2h"},"entry":true,"prior":[],"meta":{"raw":{"role":"plugin1","cmd":"resolve"},"plugin_name":"root$","plugin_fullname":"root$","sub":false,"client":false,"args":{"role":"plugin1","cmd":"resolve"},"rules":{},"id":"(fr80qezan8wm)","pattern":"cmd:resolve,role:plugin1","msgcanon":{"cmd":"resolve","role":"plugin1"},"priorpath":""},"client":false,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":29,"level":"error","when":1478044869422}
should reach here @1
```
Could someone explain the different between these and why the first case doesn't reach the console logs?

**Comment by StarpTech** [comment]
Lots of people misunderstood the concept of error handling in seneca. Hope it helps
https://github.com/senecajs/seneca/issues/574#issuecomment-254540031

Big talk https://github.com/senecajs/seneca/issues/398

**Comment by ygist** [comment]
That makes sense. thanks @StarpTech!
