### ISSUE TITLE
Gate-executor timeout when using docker.

### ISSUE THREAD

**Issue by ssmereka** [senecajs/seneca#586]
When I use Seneca specifically in a docker container in linux I get timeout errors like the following:

```
2016-11-18T21:31:20.461Z bkqsdzvggnf8/1479504668771/29/- ERROR	act	root$       	OUT		method:register,model:appids,service:maids	11125	{id:1,ids:[1],method:register,model:appids,service:maids,user:{id:1},version:0}	ENTRY	(jpaja3fv57ec)	-	seneca: Action method:register,model:appids,service:maids failed: [TIMEOUT:59xhvol3ugur/ggym0atiq7df:11111<1479504680450-1479504669333:undefined].	act_execute	{id:59xhvol3ugur/ggym0atiq7df,gate:false,ungate:false,desc:null,time:{start:1479504669333,end:1479504680450},me	Error: [TIMEOUT:59xhvol3ugur/ggym0atiq7df:11111<1479504680450-1479504669333:undefined]
    at Timeout._onTimeout (/usr/src/app/node_modules/seneca/node_modules/gate-executor/gate-executor.js:112:21)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

This error occurs when I return my result to the callback method:
```
seneca.add(PATTERN_BASE+'register', function (msg, cb) {
    // blah blah blah
    cb(undefined, { data: "here is some data"});
}
```

**Any ideas on why this is not working?**

The only thing left I can think of is seneca is using the plugin [seneca-mesh](https://github.com/mirceaalexandru/seneca-mesh) which may require some extra information like the current system's IP address.  As described in the linked page's examples 1, 2, and 3.

## Additional Info
See the full code example on [Circle CI](https://circleci.com/gh/smartdevicelink/sdl_shaid_maids/75).

### Seneca Version:
Seneca version is 3.2.2, other package versions can be found in the [package.json](https://github.com/smartdevicelink/sdl_shaid_maids/blob/develop/package.json#L75)

### Docker Info
```
ubuntu@box1733:~/sdl_shaid_maids$ docker info
Containers: 31
Images: 29
Server Version: 1.9.1-circleci-cp-workaround
Storage Driver: btrfs
Execution Driver: lxc-1.0.8
Logging Driver: json-file
Kernel Version: 3.13.0-100-generic
Operating System: Ubuntu 14.04.4 LTS (containerized)
CPUs: 2
Total Memory: 58.97 GiB
Name: box1733.localdomain
ID: 27VI:LOP7:F6XM:CITM:KX3V:ACDB:GHLC:YPKT:GG4W:6ZCR:42GB:PO6G
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 19
 System Time: 2016-11-18T21:57:05.774319822Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by katsanva** [comment]
I've had issues with `seneca-mesh` and docker that looks very similar to yours.
In my case, when using `seneca-mesh` with docker you need to specify at least container's hostname/ip when using `seneca.use('mesh', {host})` so that mesh can even start.

**Comment by ssmereka** [comment]
I tried specifying the host's IP, but I get the same error.  See this [circle ci build](https://circleci.com/gh/smartdevicelink/sdl_shaid_maids/76).

**Comment by katsanva** [comment]
Check [this](https://docs.docker.com/engine/reference/run/#/entrypoint-default-command-to-execute-at-runtime) to avoid building another image just for tests.

Anyway, the only thing I can see is that in [config for circle-ci](https://github.com/smartdevicelink/sdl_shaid_maids/blob/develop/config/test-circleci.json#L24) you state a pin, that differs a bit from [pin, you are adding actors on](https://github.com/smartdevicelink/sdl_shaid_maids/blob/master/app/appids/appid_seneca.js#L16). 

Not sure, but it can do the trick.

**Comment by rjrodger** [comment]
Docker does make life a little more complex as you have to get the networking right. Seneca-mesh needs a shared network to work, so you need to create a docker overlay network. Also Docker overlay networks do not support multicast, so to find the base nodes, you either need to define a set of fixed IPs, and set them as configuration, or, if using docker swarm, you need to use a registry like consul to dynamically store the base node IPs. See the test code for a swarm example: https://github.com/senecajs/seneca-mesh/tree/master/test/docker
Simplest approach is probably: https://github.com/senecajs/seneca-mesh/tree/master/examples/40-consul-discovery

**Comment by rjrodger** [comment]
To answer your original question - the timeout is caused the lack of a network route, caused by Docker's network configuration

**Comment by rjrodger** [comment]
The demo code in https://github.com/nodezoo and https://github.com/senecajs/ramanujan now has working Docker examples
