### ISSUE TITLE
errorstack in option object received by action function 

### ISSUE THREAD

**Issue by Pulankit-so** [senecajs/seneca#604]
@Hello, Lately playing around with  @Seneca(v3.2) microservices.I have found a very interesting behavior that when I am trying to pass function in message object the key is not received by the action function. For example consider this server.js code
```
var seneca = require('seneca')()

seneca.use(testService)
seneca.listen(2000)
seneca.ready(()=>{
  console.log('service is ready')
})

function testService(options){
	this.add({cmd:'say'},function(option,done){
		console.log('what',option.what)
		console.log('say',option.say)
		done()
	})
}
``` 

when tested with 
```
var seneca = require('seneca')({log:'test'})
seneca.test((err)=>{
	console.log('client error',err)
})

seneca.client(2000)
seneca.ready(()=>{
	seneca.act({
		cmd:'say',
		what:'hello',
		say:function(data){
			console.log('say ',data)
		}
	},(err,data)=>{
		if(err){
		 return console.log('error',err)
		}
		return console.log('success!')
	})
})
```
the `say` argument is not received by testService i.e 

`what`==> `hello`
`say`==>`undefined`

Hence seneca is _removing any function passed in message_ . this worked fine when the act is executed on the same instance of seneca on which add was called.Please look into the issue asap

**Comment by StarpTech** [comment]
Hi @pulankitpanjwani you cant transfer functions over the wire you have to serialize them. It works in the same process because seneca dont serialize the data in the same process.

**Comment by pulankitpanjwani** [comment]
Ohh I see .. alright will find a workaround for the same.Thanks for the response:+1: :-)

**Comment by pulankitpanjwani** [comment]
also , when i run the act in test mode there is some error in option object recieved by function
```
{ cmd: 'say',
  what: 'hello',
  'transport$': 
   { track: [ 'm8mshngsvbqa/1486728435074/14116/3.2.2/-' ],
     origin: 'm8mshngsvbqa/1486728435074/14116/3.2.2/-',
     time: { client_sent: '1486728435199' } },
  'plugin$': { name: 'transport', tag: '-' },
  'tx$': 'dbrw6wh0ytka',
  'caller$': '\n    Action call arguments and location: Error: { cmd: \'say\',  what: \'hello\',  \'transport$\':    { track: [ \'m8mshngsvbqa/1486728435074/14116/3.2.2/-\' ],     origin: \'m8mshngsvbqa/1486728435074/14116/3.2.2/-\',     time: { client_sent: \'1486728435199\' } },  \'id$\': \'2wizvbpvy3a7/dbrw6wh0ytka\',  \'plugin$\': { name: \'transport\', tag: \'-\' },  \'tx$\': \'dbrw6wh0ytka\' }\n    at internals.Utils.requestAct (/home/enuke/Pulankit/work/testwork/node_modules/seneca-transport/lib/transport-utils.js:243:12)\n    at internals.Utils.handle_request (/home/enuke/Pulankit/work/testwork/node_modules/seneca-transport/lib/transport-utils.js:236:8)\n    at Object.internals.trackHeaders (/home/enuke/Pulankit/work/testwork/node_modules/seneca-transport/lib/http.js:235:17)\n    at /home/enuke/Pulankit/work/testwork/node_modules/seneca-transport/lib/http.js:37:19\n    at IncomingMessage.<anonymous> (/home/enuke/Pulankit/work/testwork/node_modules/seneca-transport/lib/http.js:193:7)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)',
  'meta$': 
   { id: '2wizvbpvy3a7/dbrw6wh0ytka',
     tx: 'dbrw6wh0ytka',
     pattern: 'cmd:say',
     action: '(nnfluhstlaq8)',
     plugin_name: 'testService',
     plugin_tag: '-',
     prior: { chain: [], entry: true, depth: 0 },
     start: 1486728435218,
     sync: true } }
```
the service runs fine but the dont know why this `caller$` error is there(only in test mode)

**Comment by rjrodger** [comment]
@Pulankit-so in test mode this caller stack is generated in case there is an error, but it's just internal data, not an error itself
