### ISSUE TITLE
Seneca Time out errors

### ISSUE THREAD

**Issue by ymohammad** [senecajs/seneca#609]
Hi,
I am facing an issue of Session time out if the  microservice it taking more time to complete the execution. I tried it with gate$: false and also timeout$ but it is still giving me the time-out error. Here is the sample code to replicate the issue.

> **_server.js_**

```var seneca = require('seneca')();
seneca.listen({ type: 'http', host:'localhost', port:"8787"});

var delay = 34000;
seneca.add({role:'some_role', cmd: 'blokcing_call'}, function (args, done) {
  rabbitmq_consumer(done);
});

function rabbitmq_consumer(done) {
    setTimeout(function(){
        done(null, {status: 'success'}); 
    }, delay);
}
```

> **_client.js_**

```var seneca = require( 'seneca' )().client({type: 'http', host:"localhost", port:"8787"});

seneca.act({role:'some_role', cmd: 'blokcing_call', gate$: false}, function(err, resp) { 
    if(err) {
        console.log(err);
    }
    console.log('Client Blocking call registed.', resp); 
});
```

At when executing the client.js, it is still giving me time-out error. 

Following is the error logs.
```
(node:29176) DeprecationWarning: 'root' is deprecated, use 'global'
["client","invalid_origin",{"type":"web","host":"localhost","port":"8787","pg":"","id":"host:localhost,pg:,port:8787,type:http","role":"transpor
t","hook":"client","plugin$":{"name":"client$"},"fatal$":true,"meta$":{"mi":"hp1gawbzm7yl","tx":"rmuhtnqijb1n","id":"hp1gawbzm7yl/rmuhtnqijb1n",
"pattern":"hook:client,role:transport,type:web","action":"(nnusq5llezbu)","plugin_name":"transport","plugin_tag":"-","prior":{"chain":[],"entry"
:true,"depth":0},"start":1488298431124,"sync":true},"tx$":"rmuhtnqijb1n","path":"/act","protocol":"http","timeout":5555,"max_listen_attempts":11
,"attempt_delay":222,"serverOptions":{}},{"kind":"res","res":null,"error":{"isBoom":true,"isServer":true,"output":{"statusCode":504,"payload":{"
statusCode":504,"error":"Gateway Time-out","message":"Client request timeout"},"headers":{}}},"sync":true,"time":{"client_recv":1488298436709}}]

{"notice":"seneca: Action  failed: [TIMEOUT].","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"
seneca","msg":"seneca: Action  failed: [TIMEOUT].","details":{"message":"[TIMEOUT]","pattern":"","instance":"Seneca/th5d9h1hxy91/1488298430861/2
9176/3.3.0/-","orig$":{},"message$":"[TIMEOUT]","plugin":{}},"callpoint":"at Object.act_tm [as ontm] (C:\\Sufiyan_Files\\GitSourceCode\\mes_gaia
\\applications\\packaging\\node_modules\\seneca\\seneca.js:1041:46)"},"actid":"hlae5zs14yzb/o268wobb9rnb","msg":{"role":"some_role","cmd":"blokc
ing_call","gate$":false,"meta$":{"mi":"hlae5zs14yzb","tx":"o268wobb9rnb","id":"hlae5zs14yzb/o268wobb9rnb","pattern":"","action":"(s2t0cqsrzdmf)"
,"plugin_name":"client$","plugin_tag":"-","prior":{"chain":[],"entry":true,"depth":0},"start":1488298431094,"sync":true},"plugin$":{"name":"clie
nt$","tag":"-"},"tx$":"o268wobb9rnb"},"entry":true,"prior":[],"gate":false,"meta":{"plugin_name":"client$","plugin_tag":"-","plugin_fullname":"c
lient$","raw":{"client$":true,"internal$":{"catchall":true}},"sub":false,"client":true,"args":{},"rules":{},"id":"(s2t0cqsrzdmf)","pattern":"","
msgcanon":{},"priorpath":""},"client":true,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":22307,"level":"error","when":14882
98453409}
{ Error: [TIMEOUT]
    at Object.act_tm [as ontm] (C:\Sufiyan_Files\GitSourceCode\mes_gaia\applications\packaging\node_modules\seneca\seneca.js:1041:46)
    at Timeout.timeout_check [as _onTimeout] (C:\Sufiyan_Files\GitSourceCode\mes_gaia\applications\packaging\node_modules\gate-executor\gate-exe
cutor.js:216:16)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  eraro: true,
  orig:
   Error: [TIMEOUT]
       at Object.act_tm [as ontm] (C:\Sufiyan_Files\GitSourceCode\mes_gaia\applications\packaging\node_modules\seneca\seneca.js:1041:46)
       at Timeout.timeout_check [as _onTimeout] (C:\Sufiyan_Files\GitSourceCode\mes_gaia\applications\packaging\node_modules\gate-executor\gate-
executor.js:216:16)
       at ontimeout (timers.js:365:14)
       at tryOnTimeout (timers.js:237:5)
       at Timer.listOnTimeout (timers.js:207:5),
  code: 'act_execute',
  seneca: true,
  package: 'seneca',
  msg: 'seneca: Action  failed: [TIMEOUT].',
  details:
   { message: '[TIMEOUT]',
     pattern: '',
     fn: { [Function: transport_client] id: 'host:localhost,pg:,port:8787,type:http' },
     cb: [Function],
     instance: 'Seneca/th5d9h1hxy91/1488298430861/29176/3.3.0/-',
     'orig$':
      Error: [TIMEOUT]
          at Object.act_tm [as ontm] (C:\Sufiyan_Files\GitSourceCode\mes_gaia\applications\packaging\node_modules\seneca\seneca.js:1041:46)
          at Timeout.timeout_check [as _onTimeout] (C:\Sufiyan_Files\GitSourceCode\mes_gaia\applications\packaging\node_modules\gate-executor\ga
te-executor.js:216:16)
          at ontimeout (timers.js:365:14)
          at tryOnTimeout (timers.js:237:5)
          at Timer.listOnTimeout (timers.js:207:5),
     'message$': '[TIMEOUT]',
     plugin: {} },
  callpoint: 'at Object.act_tm [as ontm] (C:\\Sufiyan_Files\\GitSourceCode\\mes_gaia\\applications\\packaging\\node_modules\\seneca\\seneca.js:1
041:46)' }
Client Blocking call registed. undefined
{"kind":"notice","notice":"hello seneca th5d9h1hxy91/1488298430861/29176/3.3.0/-","level":"info","when":1488298453415}
```

**Comment by rjrodger** [comment]
You can use a timeout$ directive inside the message: `seneca.act({timeout$:99999, ...})`

Also, if the server process is very long, consider using two asynchronous messages instead of a request-response.

**Comment by Yuvaleros** [comment]
Hi @rjrodger, Can you please elaborate on using "two asynchronous messages instead of a request-response"?

**Comment by rjrodger** [comment]
@Yuvaleros This is the scatter-gather pattern - you can see it here: https://github.com/nodezoo/nodezoo-info

Basically, send out a message of one type, and wait for other messages to come back in, instead of using the message response. This allows for multiple responses.

**Comment by Yuvaleros** [comment]
Thanks! Just what I was looking for!

**Comment by rjrodger** [comment]
My pleasure!

**Comment by rodmaz** [comment]
I am trying to use the `timeout$` attribute inside a `seneca.act` and it is not working properly. Request keeps timing out in about 5 sec. Any hints what may be happening?

**Comment by dcboy** [comment]
@rodmaz me too,i also set timeout$ options but not work for me!
