### ISSUE TITLE
Seneca + Chairo - Error on default logger

### ISSUE THREAD

**Issue by otaviosoares** [senecajs/seneca#611]
I'm getting this error whenever an error occurs in my service. I dug into seneca and found it was caused by the req$ key that Chairo adds to seneca request (https://github.com/hapijs/chairo/blob/master/lib/index.js#L132) which leads Stringify to fail. Removing the key before logging fixes the issue.

I'm not sure if it should be fixed on seneca side or chairo's. To be honest IDK whats the purpose of req$.

Anybody else with this issue?

`Debug: internal, implementation, error 
RangeError: Invalid string length
at join (native)
at Object.stringify (native)
at Object.stringify (/home/otaviosoares/.nvm/v4.4.4/lib/node_modules/fuge/node_modules/core-js/modules/es6.symbol.js:224:23)
at stringify (/home/otaviosoares/Projects/artyou/artyou-services/artyou-webapi/node_modules/json-stringify-safe/stringify.js:5:15)
at Object.logger (/home/otaviosoares/Projects/artyou/artyou-services/artyou-webapi/node_modules/seneca/lib/logging.js:54:19)
at Seneca.log (/home/otaviosoares/Projects/artyou/artyou-services/artyou-webapi/node_modules/seneca/seneca.js:1603:23)
at Seneca.log_modifier (/home/otaviosoares/Projects/artyou/artyou-services/artyou-webapi/node_modules/seneca/seneca.js:1641:9)
at Seneca.prepare_log_data [as log] (/home/otaviosoares/Projects/artyou/artyou-services/artyou-webapi/node_modules/seneca/seneca.js:1621:9)
at Seneca.log_modifier (/home/otaviosoares/Projects/artyou/artyou-services/artyou-webapi/node_modules/seneca/seneca.js:1641:9)
at Function.prepare_log_data [as error] (/home/otaviosoares/Projects/artyou/artyou-services/artyou-webapi/node_modules/seneca/seneca.js:1621:9)`

Thanks

**Versions**
Seneca: 3.3.0
Chairo: 3.0.0
Hapi: 13.5.3
Node: 4.4

**Comment by sberryman** [comment]
I'm experiencing this as well, extremely annoying and so glad you posted this. `req$` is also of no use to me and wish there was an easy way to turn it off

**Comment by sberryman** [comment]
I added an issue on the chairo side as it seems specific to using chairo. However, I'm extremely grateful you posted the issue here as this is where I looked first.

**Comment by otaviosoares** [comment]
Yeah, it makes more sense to treat it on chairo's side. I'm closing this issue in favor of yours.
