### ISSUE TITLE
Console output in test

### ISSUE THREAD

**Issue by rodolfoamarques** [senecajs/seneca#622]
Hey guys!

I have around 10 microservices developed using seneca. I have been unit testing them, following the example in the [ramanujan project](https://github.com/senecajs/ramanujan) ( for example like in the [POST](https://github.com/senecajs/ramanujan/tree/master/post) service).

A quick "best practice" question: is this the standard/recommended way to unit test a Seneca microservice? Splitting the service instantiation and the actual logic, with the test suite mimicking the instantiation and using the logic only?

Anyways on to the issue i'm facing: I've set the seneca instance to set mode as in the [mentioned example](https://github.com/senecajs/ramanujan/blob/master/post/test/post-test.js#L58) and set the 'log' option to silent with `return Seneca({ tags: 'service-test', log: 'silent' }).test( end ).use( require('../service-logic') );`
Still, when i run the test suite and test failure scenarios, i always have errors logged to the console by seneca. For example, in the following scenario I have a unit test to see if i get an error when trying to delete a user with a non-existing id in the database:
```
51/ap	act/ERR	y9/la	cmd:delete,role:user	{role:'user',cmd:'delete',data:{_id:'nonexisting_'}}	seneca: Action cmd:delete,role:user failed: user_not_found.	

Error: user_not_found
    at db.collection.updateOne.then.then.catch.err (/home/rodolfo/Documents/contract-services/services/user-service-v2/users-logic.js:385:155)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/home/rodolfo/Documents/contract-services/services/user-service-v2/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/rodolfo/Documents/contract-services/services/user-service-v2/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/rodolfo/Documents/contract-services/services/user-service-v2/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/rodolfo/Documents/contract-services/services/user-service-v2/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/rodolfo/Documents/contract-services/services/user-service-v2/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/rodolfo/Documents/contract-services/services/user-service-v2/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/rodolfo/Documents/contract-services/services/user-service-v2/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

    Action call arguments and location: Error: { role: 'user', cmd: 'delete', data: { _id: 'nonexisting_' } }
    at /home/rodolfo/Documents/contract-services/services/user-service-v2/test/users-test.js:4383:12
    at Immediate.setImmediate (/home/rodolfo/Documents/contract-services/services/user-service-v2/node_modules/lab/lib/runner.js:672:36)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

  ✔ 1) role:user, cmd:delete - delete a non-existing user (55 ms)
```

I would assume that when using 'log: silent' this error log would not be outputted to the console and I would only have the test passed line. Am I wrong? What can I do to suppress these logs?

**Comment by rjrodger** [comment]
@rodolfoamarques seneca.test overrides previous log settings :)

If your test uses errors directly, then don't use seneca.test
Instead, validate the errors in the callback, or use the seneca.error method

let me know if I understood correctly

**Comment by rodolfoamarques** [comment]
Hey @rjrodger ! Thanks for the answer!

So what I get from you is that you can control the log level for seneca, but when in test mode it is what it is and you can't change it. Is this correct?

I'm not sure if I follow your next comment about not using seneca.test(). So, what my tests try to cover are both success scenarios and failure scenarios. Meaning that in some scenarios the method performs the action that it is supposed to without issues, and in others (most of them) I just throw a bunch of garbage to it and expect it to return errors when handling that garbage (and my test passes if the method is actually returning those errors). What I'm understanding from your answer is that in these scenarios where I actually do expect errors I shouldn't use the seneca.test() mode and just validate the error myself in the callback (or possibly use the seneca.error() to handle those errors). Is that it?

**Comment by rjrodger** [comment]
Correct - `seneca.test` is just a convenience for unit testing.

That said I think you have uncovered a use-case that needs to be supported, so marking this as a feature! Thank you :)

**Comment by rodolfoamarques** [comment]
Awesome @rjrodger !

Off we go to make the world a better palce! ;)
