### ISSUE TITLE
FATAL: act cannot receive error

### ISSUE THREAD

**Issue by zhaoyao91** [senecajs/seneca#664]
I have such  code
```
  seneca.add({role, cmd: 't1'}, (req, reply) => {
    reply(new Error('NO!!!!!!!!!!!'))
  })

  seneca.add({role, cmd: 't2'}, (req, reply) => {
    seneca.act({role, cmd: 't1'}, (err, res) => {
      if (err) console.error('!!!!!!!!!!!!!!!!!!!!!!!ERR', err)
      else console.log('!!!!!!!!!!!!!!!!!!RECEIVE', res)
      reply(err, res)
    })
  })
```

when I call {role, cmd: 't1'} by http, I can receive all error msg and status code 500.
but if I call {role, cmd: 't2'} by http, the seneca app just CRASH!!!

```
{"kind":"notice","notice":"hello seneca gxrtb7sg5lak/1499916877023/27805/3.4.1/-","level":"info","seneca":"gxrtb7sg5lak/1499916877023/27805/3.4.1/-","when":1499916877436}
{"notice":"seneca: Action cmd:t1,role:i-authentication failed: NO!!!!!!!!!!!.","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:t1,role:i-authentication failed: NO!!!!!!!!!!!.","details":{"message":"NO!!!!!!!!!!!","pattern":"cmd:t1,role:i-authentication","instance":"Seneca/gxrtb7sg5lak/1499916877023/27805/3.4.1/-","orig$":{},"message$":"NO!!!!!!!!!!!","plugin":{}},"callpoint":"at Seneca.seneca.add (/Users/zhaoyao/workspace/micro/i-authentication/service.js:50:11)"},"actid":"gnojqw8h7fqk/7g9s8q5rf50q","msg":{"role":"i-authentication","cmd":"t1","transport$":{"track":[],"origin":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36","time":{"client_sent":1499916894326}},"id$":"gnojqw8h7fqk"},"meta":{"start":1499916894327,"end":1499916894328,"pattern":"cmd:t1,role:i-authentication","action":"_30","mi":"gnojqw8h7fqk","tx":"7g9s8q5rf50q","id":"gnojqw8h7fqk/7g9s8q5rf50q","instance":"gxrtb7sg5lak/1499916877023/27805/3.4.1/-","tag":"-","seneca":"3.4.1","version":"0.1.0","gate":false,"fatal":false,"local":false,"timeout":22222,"plugin":{"name":"service","tag":"-","fullname":"service"},"parents":[],"sync":true,"trace":[],"sub":null,"data":null,"err":null,"err_trace":null,"error":true,"empty":null},"actdef":{"plugin_name":"service","plugin_tag":"-","plugin_fullname":"service","raw":{"role":"i-authentication","cmd":"t1"},"plugin":{"name":"service","tag":"-","fullname":"service"},"sub":false,"client":false,"rules":{},"id":"_30","name":"","pattern":"cmd:t1,role:i-authentication","msgcanon":{"cmd":"t1","role":"i-authentication"},"priorpath":""},"client":false,"listen":true,"transport":{"track":[],"origin":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36","time":{"client_sent":1499916894326}},"kind":"act","case":"ERR","duration":1,"level":"error","plugin_name":"service","plugin_tag":"-","pattern":"cmd:t1,role:i-authentication","seneca":"gxrtb7sg5lak/1499916877023/27805/3.4.1/-","when":1499916894334}
{"notice":"seneca: Action cmd:t1,role:i-authentication failed: NO!!!!!!!!!!!.","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:t1,role:i-authentication failed: NO!!!!!!!!!!!.","details":{"message":"NO!!!!!!!!!!!","pattern":"cmd:t1,role:i-authentication","instance":"Seneca/gxrtb7sg5lak/1499916877023/27805/3.4.1/-","orig$":{},"message$":"NO!!!!!!!!!!!","plugin":{}},"callpoint":"at Seneca.seneca.add (/Users/zhaoyao/workspace/micro/i-authentication/service.js:50:11)"},"actid":"k1bb24b6wbc1/dhl4obob327y","msg":{"role":"i-authentication","cmd":"t1","plugin$":{"name":"service","tag":"-","fullname":"service"},"fatal$":true,"tx$":"dhl4obob327y"},"meta":{"start":1499916896860,"end":1499916896861,"pattern":"cmd:t1,role:i-authentication","action":"_30","mi":"yenxkz7abw06","tx":"dhl4obob327y","id":"yenxkz7abw06/dhl4obob327y","instance":"gxrtb7sg5lak/1499916877023/27805/3.4.1/-","tag":"-","seneca":"3.4.1","version":"0.1.0","gate":false,"fatal":true,"local":false,"timeout":22222,"plugin":{"name":"service","tag":"-","fullname":"service"},"parents":[["name:service,plugin:define,role:seneca,seq:3,tag:undefined","k1bb24b6wbc1/dhl4obob327y","gxrtb7sg5lak/1499916877023/27805/3.4.1/-","-","0.1.0",1499916877343,1499916877395,false,"plugin_definition_9"]],"sync":true,"trace":[],"sub":null,"data":null,"err":null,"err_trace":null,"error":true,"empty":null},"actdef":{"plugin_name":"service","plugin_tag":"-","plugin_fullname":"service","raw":{"role":"i-authentication","cmd":"t1"},"plugin":{"name":"service","tag":"-","fullname":"service"},"sub":false,"client":false,"rules":{},"id":"_30","name":"","pattern":"cmd:t1,role:i-authentication","msgcanon":{"cmd":"t1","role":"i-authentication"},"priorpath":""},"client":false,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":1,"level":"error","plugin_name":"service","pattern":"cmd:t1,role:i-authentication","seneca":"gxrtb7sg5lak/1499916877023/27805/3.4.1/-","when":1499916896862}
[]


Seneca Fatal Error
==================

Message: seneca: Action cmd:t1,role:i-authentication failed: NO!!!!!!!!!!!.

Code: act_execute

Details: { message: 'NO!!!!!!!!!!!',
  pattern: 'cmd:t1,role:i-authentication',
  fn: [Function],
  cb: [Function],
  instance: 'Seneca/gxrtb7sg5lak/1499916877023/27805/3.4.1/-',
  callpoint: undefined,
  'orig$': 
   Error: NO!!!!!!!!!!!
       at Seneca.seneca.add (/Users/zhaoyao/workspace/micro/i-authentication/service.js:50:11)
       at Object.intern.execute_action (/Users/zhaoyao/workspace/micro/i-authentication/node_modules/seneca/seneca.js:1306:15)
       at Object.act_fn [as fn] (/Users/zhaoyao/workspace/micro/i-authentication/node_modules/seneca/seneca.js:896:18)
       at Immediate.processor (/Users/zhaoyao/workspace/micro/i-authentication/node_modules/gate-executor/gate-executor.js:136:14)
       at runCallback (timers.js:800:20)
       at tryOnImmediate (timers.js:762:5)
       at processImmediate [as _immediateCallback] (timers.js:733:5),
  'message$': 'NO!!!!!!!!!!!',
  plugin: {} }

Stack: 
    at Seneca.seneca.add (/Users/zhaoyao/workspace/micro/i-authentication/service.js:50:11)
    at Object.intern.execute_action (/Users/zhaoyao/workspace/micro/i-authentication/node_modules/seneca/seneca.js:1306:15)
    at Object.act_fn [as fn] (/Users/zhaoyao/workspace/micro/i-authentication/node_modules/seneca/seneca.js:896:18)
    at Immediate.processor (/Users/zhaoyao/workspace/micro/i-authentication/node_modules/gate-executor/gate-executor.js:136:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

Instance: Seneca/gxrtb7sg5lak/1499916877023/27805/3.4.1/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance)
    at Object.intern.handle_reply (/Users/zhaoyao/workspace/micro/i-authentication/node_modules/seneca/seneca.js:1349:23)

When: 2017-07-13T03:34:56.869Z

Log: {kind:null,plugin:seneca,tag:3.4.1,id:gxrtb7sg5lak/1499916877023/27805/3.4.1/-,code:act_execute,notice:seneca: 

Node:
  { http_parser: '2.7.0', node: '8.1.2', v8: '5.8.283.41', uv: '1.12.0', zlib: '1.2.11', ares: '1.10.1-DEV', modules: '57', openssl: '1.0.2l', icu: '59.1', unicode: '9.0', cldr: '31.0.1', tz: '2017b' },
  { debug: false, uv: true, ipv6: true, tls_npn: true, tls_alpn: true, tls_sni: true, tls_ocsp: true, tls: true },
  [ 'Binding contextify', 'Binding natives', 'Binding config', 'NativeModule events', 'Binding async_wrap', 'Binding icu', 'NativeModule util', 'Binding uv', 'NativeModule buffer', 'Binding buffer', 'Binding util', 'NativeModule internal/util', 'NativeModule internal/errors', 'Binding constants', 'NativeModule internal/buffer', 'NativeModule timers', 'Binding timer_wrap', 'NativeModule internal/linkedlist', 'NativeModule async_hooks', 'NativeModule assert', 'NativeModule internal/process', 'NativeModule internal/process/warning', 'NativeModule internal/process/next_tick', 'NativeModule internal/process/promises', 'NativeModule internal/process/stdio', 'NativeModule internal/url', 'NativeModule internal/querystring', 'NativeModule querystring', 'Binding url', 'NativeModule path', 'NativeModule module', 'NativeModule internal/module', 'NativeModule vm', 'NativeModule fs', 'Binding fs', 'NativeModule stream', 'NativeModule internal/streams/legacy', 'NativeModule _stream_readable', 'NativeModule internal/streams/BufferList', 'NativeModule internal/streams/destroy', 'NativeModule _stream_writable', 'NativeModule _stream_duplex', 'NativeModule _stream_transform', 'NativeModule _stream_passthrough', 'Binding fs_event_wrap', 'NativeModule internal/fs', 'NativeModule http', 'NativeModule _http_agent', 'NativeModule net', 'NativeModule internal/net', 'Binding cares_wrap', 'Binding tty_wrap', 'Binding tcp_wrap', 'Binding pipe_wrap', 'Binding stream_wrap', 'NativeModule _http_client', 'NativeModule url', 'Binding http_parser', 'NativeModule _http_common', 'NativeModule internal/freelist', 'NativeModule internal/http', 'NativeModule _http_incoming', 'NativeModule _http_outgoing', 'NativeModule _http_server', 'NativeModule https', 'NativeModule tls', 'Binding crypto', 'NativeModule _tls_common', 'NativeModule _tls_wrap', 'NativeModule crypto', 'NativeModule internal/streams/lazy_transform', 'NativeModule string_decoder', 'NativeModule _stream_wrap', 'Binding js_stream', 'Binding tls_wrap', 'NativeModule _tls_legacy', 'NativeModule os', 'Binding os', 'NativeModule dns', 'NativeModule cluster', 'NativeModule internal/cluster/master', 'NativeModule child_process', 'Binding spawn_sync', 'NativeModule internal/child_process', 'NativeModule dgram', 'Binding udp_wrap', 'Binding process_wrap', 'NativeModule internal/socket_list', 'NativeModule internal/cluster/round_robin_handle', 'NativeModule internal/cluster/utils', 'NativeModule internal/cluster/shared_handle', 'NativeModule internal/cluster/worker', 'NativeModule console', 'NativeModule tty', 'Binding signal_wrap', 'Binding inspector' ]

Process: 
  pid=27805, arch=x64, platform=darwin,
  path=/Users/zhaoyao/.nvm/versions/node/v8.1.2/bin/node,
  argv=[ '/Users/zhaoyao/.nvm/versions/node/v8.1.2/bin/node',  '/Users/zhaoyao/workspace/micro/i-authentication' ],
  env={ npm_config_save_dev: '',  npm_config_legacy_bundling: '',  npm_config_dry_run: '',  npm_config_only: '',  npm_config_browser: '',  npm_config_viewer: 'man',  ROLE_T_HELLO_HOST: '127.0.0.1',  npm_config_also: '',  npm_config_rollback: 'true',  TERM_PROGRAM: 'Apple_Terminal',  npm_config_usage: '',  NODE: '/Users/zhaoyao/.nvm/versions/node/v8.1.2/bin/node',  NVM_CD_FLAGS: '',  npm_config_globalignorefile: '/Users/zhaoyao/.nvm/versions/node/v8.1.2/etc/npmignore',  SHELL: '/bin/bash',  TERM: 'xterm-256color',  npm_config_init_author_url: '',  npm_config_shell: '/bin/bash',  npm_config_maxsockets: '50',  npm_config_parseable: '',  npm_config_shrinkwrap: 'true',  npm_config_metrics_registry: 'https://registry.npmjs.org/',  TMPDIR: '/var/folders/k8/yz74nt2d7p71j6bbqpx_n70093vwwk/T/',  npm_config_timing: '',  npm_config_init_license: 'ISC',  Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.GCQhPmTgqG/Render',  npm_config_if_present: '',  TERM_PROGRAM_VERSION: '388.1',  npm_package_scripts_dev: 'nodemon -x \'npm start\'',  npm_config_sign_git_tag: '',  npm_config_init_author_email: '',  npm_config_cache_max: 'Infinity',  npm_config_long: '',  npm_config_local_address: '',  npm_config_cert: '',  npm_config_git_tag_version: 'true',  npm_package_dependencies_mysql: '^2.13.0',  TERM_SESSION_ID: '9FDEDEDD-8D73-4946-AA09-9562A19B23A8',  SERVICE_I_DINGDING_CONNECTOR_HOST: '127.0.0.1',  npm_config_registry: 'https://registry.npmjs.org/',  npm_config_fetch_retries: '2',  ROLE_T_HELLO_PORT: '3001',  DINGDING_APP_NAME: 'marketing',  SERVICE_I_SESSION_TCP_PORT: '4004',  npm_config_versions: '',  npm_config_key: '',  npm_config_message: '%s',  npm_package_readmeFilename: 'README.md',  npm_package_description: '',  USER: 'zhaoyao',  NVM_DIR: '/Users/zhaoyao/.nvm',  DINGDING_DOMAIN: 'ding.tap4fun.com',  npm_config_globalconfig: '/Users/zhaoyao/.nvm/versions/node/v8.1.2/etc/npmrc',  MYSQL_URL: 'mysql://mk_test:XLbKA7%2FjQ@dw.cluster-coyify1oibfl.us-west-2.rds.amazonaws.com:3306/marketing_test',  npm_config_prefer_online: '',  npm_config_always_auth: '',  npm_config_logs_max: '10',  SERVICE_I_USER_TCP_PORT: '4002',  SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.KiA4XpUDcj/Listeners',  __CF_USER_TEXT_ENCODING: '0x123DF392:0x19:0x34',  npm_execpath: '/Users/zhaoyao/.nvm/versions/node/v8.1.2/lib/node_modules/npm/bin/npm-cli.js',  npm_config_global_style: '',  npm_config_cache_lock_retries: '10',  npm_config_cafile: '',  SERVICE_I_SESSION_HOST: '127.0.0.1',  npm_package_author_name: 'zhaoyao91',  npm_config_heading: 'npm',  npm_config_offline: '',  npm_config_searchlimit: '20',  npm_config_proprietary_attribs: 'true',  npm_config_fetch_retry_mintimeout: '10000',  npm_config_json: '',  npm_config_access: '',  npm_config_argv: '{"remain":[],"cooked":["start"],"original":["start"]}',  PATH: '/Users/zhaoyao/.nvm/versions/node/v8.1.2/lib/node_modules/npm/bin/node-gyp-bin:/Users/zhaoyao/workspace/micro/i-authentication/node_modules/.bin:/Users/zhaoyao/.nvm/versions/node/v8.1.2/lib/node_modules/npm/bin/node-gyp-bin:/Users/zhaoyao/workspace/micro/i-authentication/node_modules/.bin:/Users/zhaoyao/.nvm/versions/node/v8.1.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',  npm_config_allow_same_version: '',  npm_package_dependencies_seneca: '^3.4.1',  npm_config_https_proxy: '',  npm_config_engine_strict: '',  npm_config_description: 'true',  _: '/Users/zhaoyao/.nvm/versions/node/v8.1.2/bin/node',  npm_config_userconfig: '/Users/zhaoyao/.npmrc',  npm_config_init_module: '/Users/zhaoyao/.npm-init.js',  npm_package_dependencies_promisify_seneca: '^1.0.0',  PWD: '/Users/zhaoyao/workspace/micro/i-authentication',  npm_config_user: '306049938',  npm_config_node_version: '8.1.2',  npm_lifecycle_event: 'start',  npm_config_ignore_prepublish: '',  npm_config_save: 'true',  npm_config_editor: 'vi',  npm_config_auth_type: 'legacy',  npm_package_name: 'i-authentication',  LANG: 'zh_CN.UTF-8',  npm_config_script_shell: '',  npm_config_tag: 'latest',  npm_config_global: '',  npm_config_progress: 'true',  npm_package_scripts_start: 'node --harmony .',  npm_config_ham_it_up: '',  npm_config_searchstaleness: '900',  npm_config_optional: 'true',  XPC_FLAGS: '0x0',  npm_config_save_prod: '',  npm_config_force: '',  npm_config_bin_links: 'true',  npm_config_searchopts: '',  npm_config_depth: 'Infinity',  npm_package_main: 'index.js',  SERVICE_I_USER_HOST: '127.0.0.1',  npm_config_sso_poll_frequency: '500',  npm_config_rebuild_bundle: 'true',  npm_package_version: '0.0.1',  XPC_SERVICE_NAME: '0',  npm_config_unicode: 'true',  SHLVL: '4',  HOME: '/Users/zhaoyao',  npm_config_fetch_retry_maxtimeout: '60000',  npm_config_ca: '',  npm_config_tag_version_prefix: 'v',  npm_config_strict_ssl: 'true',  npm_config_sso_type: 'oauth',  npm_config_scripts_prepend_node_path: 'warn-only',  npm_config_save_prefix: '^',  npm_config_loglevel: 'notice',  npm_config_save_exact: '',  npm_config_dev: '',  npm_config_group: '742773148',  npm_config_fetch_retry_factor: '10',  npm_config_version: '',  npm_config_prefer_offline: '',  npm_config_cache_lock_stale: '60000',  npm_package_dependencies_knex: '^0.13.0',  npm_config_cache_min: '10',  SERVICE_I_DINGDING_CONNECTOR_TCP_PORT: '4003',  npm_config_searchexclude: '',  npm_config_cache: '/Users/zhaoyao/.npm',  LOGNAME: 'zhaoyao',  npm_lifecycle_script: 'node --harmony .',  npm_config_color: 'true',  npm_config_proxy: '',  npm_config_package_lock: 'true',  npm_package_author_email: 'zhaoyao91@163.com',  npm_config_save_optional: '',  NVM_BIN: '/Users/zhaoyao/.nvm/versions/node/v8.1.2/bin',  DINGDING_APP_SECRET: 'EULgqJr8YTWycZQ0nZ87VeeQ6T4NUdCI',  npm_config_ignore_scripts: '',  npm_config_user_agent: 'npm/5.2.0 node/v8.1.2 darwin x64',  npm_config_cache_lock_wait: '10000',  PORT: '3000',  npm_config_production: '',  npm_config_send_metrics: '',  npm_config_save_bundle: '',  npm_config_umask: '0022',  npm_config_init_version: '1.0.0',  WEB_PORT: '3000',  npm_config_init_author_name: '',  npm_config_git: 'git',  npm_config_scope: '',  SECURITYSESSIONID: '186a6',  npm_config_onload_script: '',  npm_config_unsafe_perm: 'true',  npm_config_tmp: '/var/folders/k8/yz74nt2d7p71j6bbqpx_n70093vwwk/T',  npm_package_devDependencies_nodemon: '^1.11.0',  npm_node_execpath: '/Users/zhaoyao/.nvm/versions/node/v8.1.2/bin/node',  npm_config_link: '',  npm_config_prefix: '/Users/zhaoyao/.nvm/versions/node/v8.1.2' }




SENECA TERMINATED (on timeout) at 2017-07-13T03:35:07.984Z.


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! i-authentication@0.0.1 start: `node --harmony .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the i-authentication@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhaoyao/.npm/_logs/2017-07-13T03_35_07_998Z-debug.log
[nodemon] failed to start process, possible issue with exec arguments
events.js:187
      throw err;
      ^

Error: Unhandled "error" event. (2)
    at Bus.emit (events.js:185:19)
    at ChildProcess.<anonymous> (/Users/zhaoyao/workspace/micro/i-authentication/node_modules/nodemon/lib/monitor/run.js:126:11)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-authentication@0.0.1 dev: `nodemon -x 'npm start'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the i-authentication@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhaoyao/.npm/_logs/2017-07-13T03_35_08_033Z-debug.log
```

**Comment by kryptstorm** [comment]
If you reply with an error, seneca will throw an error and app will crash. This is a rule.
So, if you want receive error to handle , you should do like code bellow 
```

 seneca.add({role, cmd: 't1'}, (req, reply) => {
    reply(null, {error$: new Error('NO!!!!!!!!!!!')})
  })

  seneca.add({role, cmd: 't2'}, (req, reply) => {
    seneca.act({role, cmd: 't1'}, (err, res) => {
      if (err) console.error('!!!!!!!!!!!!!!!!!!!!!!!ERR', err)
      else console.log('!!!!!!!!!!!!!!!!!!RECEIVE', res)
      reply(err, res) // res is object - {error$: new Error('NO!!!!!!!!!!!')}
    })
  })
```

Now, you can return error status and message to user by http

**Comment by davide-talesco** [comment]
The real problem is that you are using arrow functions!! (because arrow functions do not bind this )
if your plugin looks like below it works as expected:

```node
module.exports = function plugin(options){
 // this seneca instance is fatal because it belong to the plugin initialization
  const seneca = this;

  function t1(req, reply){
    reply(new Error('NO!!!!!!!!!!!'))
  }

  function t2(req, reply){
   // this is a non fatal instance of seneca
    this.act({cmd: 't1'}, (err, res) => {
      if (err) console.error('!!!!!!!!!!!!!!!!!!!!!!!ERR', err);
      else console.log('!!!!!!!!!!!!!!!!!!RECEIVE', res);
      reply(err, res)
    })
  }

  seneca.add({cmd: 't1'}, t1);

  seneca.add({cmd: 't2'}, t2);
};
```
check the following link for more details on fatal vs non fatal errors!
