### ISSUE TITLE
Get Error: Client request timeout when test the example api(hex-color-service) at high frequency

### ISSUE THREAD

**Issue by ma642** [senecajs/seneca#689]
I run the example 20-local-dev-mesh of seneca-mesh (which use seneca 3.4.3). Every thing is fine when I call the api via http API http://127.0.0.1:8000/api/color/hex?color=red. Then, I try to do some simple performance test, I use ApacheBenchmark to call the same api with 100 concurrent users, the total requests are 10,000. The test result below.

ab -n 10000 -c 100 http://127.0.0.1:8000/api/color/hex?color=red
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:        
Server Hostname:        127.0.0.1
Server Port:            8000

Document Path:          /api/color/hex?color=red
Document Length:        34 bytes

Concurrency Level:      100
Time taken for tests:   44.129 seconds
Complete requests:      10000
Failed requests:        50
   (Connect: 0, Receive: 0, Length: 50, Exceptions: 0)
Non-2xx responses:      50
Total transferred:      2461850 bytes
HTML transferred:       342300 bytes
Requests per second:    226.61 [#/sec] (mean)
Time per request:       441.288 [ms] (mean)
Time per request:       4.413 [ms] (mean, across all concurrent requests)
Transfer rate:          54.48 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0   97 1111.8      0   14387
Processing:     5  344 401.9    322    5805
Waiting:        5  343 401.9    322    5804
Total:          5  440 1176.9    323   14697

Percentage of the requests served within a certain time (ms)
  50%    323
  66%    336
  75%    353
  80%    372
  90%    415
  95%    470
  98%    618
  99%   5622
 100%  14697 (longest request)

I find that the there are 50 failed requests. I find the 'Client request timeout' error in the api-service log.

51124/h6/api	act/ERR/s	9d/pn	format:hex,role:color	{role:'color',format:'hex',color:'red'}	transport_client_31	seneca: Action format:hex,role:color failed: Client request timeout.	

Error: Client request timeout
    at internals.Utils.handle_response (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:71:11)
    at /Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/seneca/node_modules/seneca-transport/lib/http.js:154:25
    at request (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:509:20)
    at finish (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:220:20)
    at wrapped (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/hoek/lib/index.js:871:20)
    at Timeout.setTimeout (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:231:20)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

    Action call arguments and location: { role: 'color', format: 'hex', color: 'red' }
    at handler (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/examples/20-local-dev-mesh/api-service.js:22:16)
    at Object.internals.handler (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/hapi/lib/handler.js:96:36)
    at request._protect.run (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/hapi/lib/handler.js:30:23)
    at internals.Protect.run (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/hapi/lib/protect.js:62:12)
    at exports.execute (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/hapi/lib/handler.js:24:22)
    at each (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/hapi/lib/request.js:380:16)
    at iterate (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/items/lib/index.js:36:13)
    at done (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/items/lib/index.js:28:25)
    at internals.Auth._authenticate (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/hapi/lib/auth.js:222:16)
    at internals.Auth.authenticate (/Users/develper/Documents/uschool/sourcecode/iawaken-pc/microservice/scenecatest/seneca-mesh/node_modules/hapi/lib/auth.js:197:17) 

It's looks like there is something wrong with the seneca service but I can not get any error message from the seneca service log. But I find that  there is few seconds that the seneca service does not output any thing(console log). The senceca service must do some clear work that can not response the client at that period(I guess). Is there anyone can help to  determine the issue?

**Comment by ryanfields** [comment]
I suspect this is because you don't have enough listeners running to handle 100 concurrent requests.

Suppose you only have 10 instances of seneca listening for a given pattern.  You send 100 requests all at the same time.  Seneca queues them all roughly at the same time, so their timeout counters all start at the same time.  But, your 10 listeners need a bit of time to process each request, so 10 get processed immediately, 10 more get processed slightly later, and so on.  The timeout starts when the message was sent, not when the listener received it, so if it's taking your listeners a while to get around to processing messages 50-100, messages 50-100 will timeout before they can be handled.

You'd need to either add more listeners to keep up with you concurrency demand, or reduce your concurrency target.

**Comment by ma642** [comment]
@ryanfields I think you are right. I find there are so tcp connections on TIME_WAIT state during the test. The api-service can not issue more TCP(HTTP) connect to real seneca-service any more. 
I think several solutions can solve the problem, such as decrease the tcp time wait , or make the seneca-service transport close connection immediately after client close the connection.  I will try to  do some performance tuning work to  evaluate the seneca's performance roughly.
