### ISSUE TITLE
Seneca TIMEOUT error

### ISSUE THREAD

**Issue by ohmtrivedi** [senecajs/seneca#706]
Hi,
I am unable to figure out what could be the possible cause for getting TIMEOUT error from my plugin. I think it is something related to promises which I have used within my action methods. Hope somebody can help me out. Attaching the relevant code files herewith.
1. Output from the listening service for my plugin:
```
ohmtrivedi@ohm-HP-ENVY:~/Documents/ms-thesis/my-ms-app/server$ sudo node osfp_service.js 
{"kind":"notice","notice":"hello seneca skhxmfxkxts5/1529357809687/6082/3.6.0/-","level":"info","seneca":"skhxmfxkxts5/1529357809687/6082/3.6.0/-","when":1529357809911}
OS for 190.186.80.90 identified.
URL http://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=Linux+2.6.18
{"notice":"seneca: Action cmd:fp_os,role:osfp_tool failed: [TIMEOUT].","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:fp_os,role:osfp_tool failed: [TIMEOUT].","details":{"message":"[TIMEOUT]","pattern":"cmd:fp_os,role:osfp_tool","instance":"Seneca/skhxmfxkxts5/1529357809687/6082/3.6.0/-","orig$":{},"message$":"[TIMEOUT]","plugin":{}},"callpoint":"at Object.act_tm [as ontm] (/home/ohmtrivedi/Documents/ms-thesis/my-ms-app/node_modules/seneca/seneca.js:923:52)"},"actid":"fh4isb9anqyz/afj8mxwwbqfu","msg":{"role":"osfp_tool","cmd":"fp_os","remote_ip":"190.186.80.90","transport$":{"track":[],"origin":"curl/7.60.0","time":{"client_sent":1529357813024}}},"meta":{"start":1529357813024,"end":1529357857582,"pattern":"cmd:fp_os,role:osfp_tool","action":"_19","mi":"fh4isb9anqyz","tx":"afj8mxwwbqfu","id":"fh4isb9anqyz/afj8mxwwbqfu","instance":"skhxmfxkxts5/1529357809687/6082/3.6.0/-","tag":"-","seneca":"3.6.0","version":"0.1.0","timeout":22222,"custom":{},"plugin":{"name":"osfp_tool","tag":"-","fullname":"osfp_tool"},"parents":[],"sync":true,"trace":[],"sub":null,"data":null,"err":null,"err_trace":null,"error":true,"empty":null},"actdef":{"plugin_name":"osfp_tool","plugin_tag":"-","plugin_fullname":"osfp_tool","raw":{"role":"osfp_tool","cmd":"fp_os"},"plugin":{"name":"osfp_tool","tag":"-","fullname":"osfp_tool"},"sub":false,"client":false,"rules":{},"id":"_19","name":"","pattern":"cmd:fp_os,role:osfp_tool","msgcanon":{"cmd":"fp_os","role":"osfp_tool"},"priorpath":""},"client":false,"listen":true,"transport":{"track":[],"origin":"curl/7.60.0","time":{"client_sent":1529357813024}},"kind":"act","case":"ERR","duration":44558,"level":"error","plugin_name":"osfp_tool","plugin_tag":"-","pattern":"cmd:fp_os,role:osfp_tool","seneca":"skhxmfxkxts5/1529357809687/6082/3.6.0/-","when":1529357857585}
Scrapper done!
[object Object]
```
2. Output from the client request.
```
ohmtrivedi@ohm-HP-ENVY:~/Documents/ms-thesis/my-ms-app$ curl -d '{"role":"osfp_tool", "cmd":"fp_os", "remote_ip":"190.186.80.90"}' http://localhost:8080/act
{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action cmd:fp_os,role:osfp_tool failed: [TIMEOUT].","details":{"message":"[TIMEOUT]","pattern":"cmd:fp_os,role:osfp_tool","instance":"Seneca/skhxmfxkxts5/1529357809687/6082/3.6.0/-","orig$":{},"message$":"[TIMEOUT]","plugin":{}},"callpoint":"at Object.act_tm [as ontm] (/home/ohmtrivedi/Documents/ms-thesis/my-ms-app/node_modules/seneca/seneca.js:923:52)","message":"seneca: Action cmd:fp_os,role:osfp_tool failed: [TIMEOUT].","name":"Error"}
```

[codefiles.zip](https://github.com/senecajs/seneca/files/2113124/codefiles.zip)

**Comment by rjrodger** [comment]
You can't mix sync and async methods.

Also, don't use `=>` with seneca as you get the plugin `this` context instead of the action context.

**Comment by ohmtrivedi** [comment]
Hi,
I am sorry, but can you please be little more specific? Where did I mix sync and async methods? Sorry, I am beginner in NodeJS and Seneca.

And thanks for the clarification about arrow function. Does it apply to both this.add and this.act methods?

**Comment by rjrodger** [comment]
Please post this question to stackoverflow. You should also try to construct the simplest example demonstrating the issue.

**Comment by ohmtrivedi** [comment]
Hi, I have posted the question on SO: https://stackoverflow.com/questions/51736174/client-request-timeout-between-senecajs-service-and-express-api

However, I had not received any response. If you get chance, kindly have a look at it. Also, I have merely followed the Getting Started tutorial on SenecaJS website, so the code structure is almost similar to the one with tutorial, ofcourse with the change being majorly in the service/plug-in. Hope that helps.
