### ISSUE TITLE
reference error when defining dynamic plugin

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca#713]
```
seneca
      .use(function plugin0() {
        this
          .add('role:plugin0,cmd:zed', function(msg, reply) {
            this.make$('foo/bar').load$(msg.bid, reply)
          })
          .add('role:plugin0,cmd:qaz')
      })
```

generates:

```
=== SENECA FATAL ERROR ===
MESSAGE:  ::: seneca: The definition function for the plugin plugin0 has failed: Cannot create property 'plugin_name' on string 'role:plugin0,cmd:qaz' (plugins.js:258:24). This error is considered fatal as all plugins have to initialize correctly. You should test the plugin by itself to verify that it is working correctly. Also ensure that the configuration options passed to the plugin are correct. These are shown below under in the DETAILS section. There could also be a bug in the plugin. If you think that is the case, please create a github issue on the plugin's repository, and include this error report.
CODE:     ::: plugin_define
INSTANCE  :::  Seneca/lgjm62dpa8z6/1531673818164/82831/3.6.0/-
DETAILS   ::: { fullname: 'plugin0',
                message: 'Cannot create property \'plugin_name\' on string \'role:plugin0,cmd:qaz\' (plugins.js:258:24)',
                options: {},
                repo: '',
                plugin: {} }
STACK     :::  TypeError: Cannot create property 'plugin_name' on string 'role:plugin0,cmd:qaz'
               at Seneca.delegate.add (/Users/richard/Projects/seneca-folder/msg-test/node_modules/seneca/lib/plugins.js:258:24)
               at Seneca.plugin0 (/Users/richard/Projects/seneca-folder/msg-test/test/msg-test.test.js:23:12)
               at define_plugin (/Users/richard/Projects/seneca-folder/msg-test/node_modules/seneca/lib/plugins.js:303:24)
               at Seneca.plugin_definition (/Users/richard/Projects/seneca-folder/msg-test/node_modules/seneca/lib/plugins.js:89:16)
               at Object.intern.execute_action (/Users/richard/Projects/seneca-folder/msg-test/node_modules/seneca/seneca.js:1314:15)
               at Object.act_fn [as fn] (/Users/richard/Projects/seneca-folder/msg-test/node_modules/seneca/seneca.js:908:18)
               at processor (/Users/richard/Projects/seneca-folder/msg-test/node_modules/gate-executor/gate-executor.js:136:14)
               at Immediate.<anonymous> (/Users/richard/Projects/seneca-folder/msg-test/node_modules/gate-executor/gate-executor.js:240:7)
               at runCallback (timers.js:810:20)
               at tryOnImmediate (timers.js:768:5)
               at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by rjrodger** [comment]
workaround:

```
seneca
      .use(function plugin0() {
        this
          .add('role:plugin0,cmd:zed', function(msg, reply) {
            this.make$('foo/bar').load$(msg.bid, reply)
          })
          .add('role:plugin0,cmd:qaz',function(){})
      })

```
