### ISSUE TITLE
Help: CL MISSING

### ISSUE THREAD

**Issue by jfbaquerocelis** [senecajs/seneca#714]
Hello! I'm using Seneca for create two microservices, the first is the database (with sequelize) and the second is an API (with express).

The Database Microservice has some Plugins that they have actions like so:

```javascript
const listUsers = require('./actions/listUsers')
const getUser = require('./actions/getUser')
const createUser = require('./actions/createUser')
const editUser = require('./actions/editUser')
const deleteUser = require('./actions/deleteUser')

function users () {
  this.add('entity:user, action:list', listUsers)
  this.add('entity:user, action:get', getUser)
  this.add('entity:user, action:create', createUser)
  this.add('entity:user, action:edit', editUser)
  this.add('entity:user, action:delete', deleteUser)
}

module.exports = users
```

I export it and the `index.js` is like so:

```javascript
const Seneca = require('seneca')
const seneca = Seneca({
  log: {
    level: 'info',
    short: true
  },
  errhandler: err => {
    console.error({
      date: moment().format('DD-MM-YYYY HH:mm:ss'),
      name: err.name,
      message: err.message.match(/failed: (.*)/i)[1],
      sql: err.sql
    })
  }
})

seneca
  .use(userPlugin)
  .listen(3000)
```

Then, the database microservice listen on port 3000. With the API microservice I do:

```javascript
const Promise = require('bluebird')
const Seneca = require('seneca')
const _seneca = Seneca({
  log: {
    level: 'info',
    short: true
  },
  errhandler: err => {
    console.error(err)
  }
})

function seneca (req, res, next) {
  let senecaClient = _seneca.client(3000)
  req.seneca = Promise.promisifyAll(senecaClient, { suffix: '_' })

  next()
}

module.exports = seneca
```

In that way I consume the database microservice, for example:

```javascript
async function GET (req, res) {
  try {
      let user = await req.seneca.act_('entity:user, action:get', { id: req.params.user_id })

      res.status(200).json(user)
  } catch (err) {
    res.status(400).send({
      name: err.name,
      message: (err.hasOwnProperty('details')) ? err.details.message : err.message
    })
  }
}
```

the above code show how I do make the API connect to Database through Seneca for serve the info.

**THE TROUBLE**

The front-end developer have an Ember App and he make some request to my API (6 exactly) and each request goes through the next middleware:

```javascript
const Promise = require('bluebird')
const isEmpty = require('lodash/isEmpty')
const { JWT } = require('../config')
const jwt = require('jsonwebtoken')
const tokenExtractor = require('token-extractor')

let bearer = Promise.promisify(tokenExtractor, { context: tokenExtractor })
let verify = Promise.promisify(jwt.verify, { context: jwt })

async function authorizer (req, res, next) {
  try {
    let token = await bearer(req)
    let decoded = await verify(token, JWT.secret)
    let adminboard = await req.seneca.act_('entity:adminboard, action:get', { id: decoded.id })

      if (isEmpty(adminboard)) {
        throw new Error('Disculpa, el administrador no está autenticado')
      } else {
        req.data = adminboard
        req.rol = 'adminboard'
        next()
      }
  } catch (err) {
    res.status(401).send({
      name: err.name,
      message: err.message
    })
  }
}

module.exports = authorizer

```

But, I get:

```
CL MISSING { id: 626, entity: 'adminboard', action: 'get' }
{ Error: [TIMEOUT]
    at Object.act_tm [as ontm] (/home/backend/Documentos/medicall24/medicall-api/node_modules/seneca/seneca.js:936:52)
    at Timeout.timeout_check [as _onTimeout] (/home/backend/Documentos/medicall24/medicall-api/node_modules/gate-executor/gate-executor.js:216:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  eraro: true,
  orig: Error: [TIMEOUT]
    at Object.act_tm [as ontm] (/home/backend/Documentos/medicall24/medicall-api/node_modules/seneca/seneca.js:936:52)
    at Timeout.timeout_check [as _onTimeout] (/home/backend/Documentos/medicall24/medicall-api/node_modules/gate-executor/gate-executor.js:216:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5),
  code: 'act_execute',
  seneca: true,
  package: 'seneca',
  msg: 'seneca: Action  failed: [TIMEOUT].',
  details: 
   { message: '[TIMEOUT]',
     pattern: '',
     fn: { [Function: transport_client] id: 'pg:,port:3000' },
     callback: [Function],
     instance: 'Seneca/vn/-',
     callpoint: undefined,
     'orig$': Error: [TIMEOUT]
    at Object.act_tm [as ontm] (/home/backend/Documentos/medicall24/medicall-api/node_modules/seneca/seneca.js:936:52)
    at Timeout.timeout_check [as _onTimeout] (/home/backend/Documentos/medicall24/medicall-api/node_modules/gate-executor/gate-executor.js:216:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5),
     'message$': '[TIMEOUT]',
     plugin: {} },
  callpoint: 'at Object.act_tm [as ontm] (/home/backend/Documentos/medicall24/medicall-api/node_modules/seneca/seneca.js:936:52)' }
```

apologies for writing a lot :laughing: but I need a hand. Thanks for read!!

**Comment by rjrodger** [comment]
@jfbaquerocelis please post this as a question on stackoverflow
You should also try to construct a test case that is as simple as possible.
Use seneca.test('print') to get nice logs for debugging.

**Comment by jfbaquerocelis** [comment]
Hi @rjrodger ! I fixed it. The problem was the some plugins were not ready. So, I used the method "ready" for serve the microservice:

```javascript
const Promise = require('bluebird')
const Seneca = require('seneca')
const _seneca = Seneca({
  log: {
    level: 'info',
    short: true
  }
})

function seneca (req, res, next) {
  try {
    _seneca.ready(function (err) {
      if (err) {
        throw err
      } else {
        let senecaClient = this.client(3000)
        req.seneca = Promise.promisifyAll(senecaClient, { suffix: '_' })
        next()
      }
    })
  } catch (err) {
    console.error(err)
    res.status(404).json(err)
  }
}

module.exports = seneca

```
I'll close this issue. Thank you :+1: :tada:
