### ISSUE TITLE
Cannot read `sync` of undefined

### ISSUE THREAD

**Issue by tswaters** [senecajs/seneca#734]
We've recently build one of our microservices and are now receiving the error in the subject line performing what appears to be any action.

```
TypeError: Cannot read property 'sync' of undefined
    at module.exports.internals.Utils.internals.Utils.prepare_request (/app/node_modules/seneca-transport/lib/transport-utils.js:138:33)
    at Seneca.act (/app/node_modules/seneca-amqp-transport/lib/client/client-factory.js:46:26)
    at /app/node_modules/seneca-transport/lib/transport-utils.js:356:14
    at /app/node_modules/seneca-transport/lib/transport-utils.js:406:7
    at pub.awaitReply.then (/app/node_modules/seneca-amqp-transport/lib/client/client-factory.js:54:19)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:694:18)
```

The only difference I can see is the recent upgrade to 3.8.0. 

We're going to lock our version to 3.7.0.... Any ideas what might cause this error?

**Comment by rjrodger** [comment]
@tswaters thanks for reporting - now fixed in seneca-transport 3.0.0 and seneca 3.8.2
