### ISSUE TITLE
Crash in version 3.8.x

### ISSUE THREAD

**Issue by rodmaz** [senecajs/seneca#741]
In our path to upgrade to the latest version of Seneca (from 3.4.2), we found out that our micro service crashes in unit tests when we upgraded Seneca from 3.7.0 to 3.8.0. 

Where can we found what changed in version 3.8.0 to cause such a severe problem?

Basically our microservice crashes when it is accessing MongoDB. All unit tests work perfectly on 3.7.0.

```
TypeError: Illegal invocation
    at handleWriteReq (internal/stream_base_commons.js:17:21)
    at writeGeneric (internal/stream_base_commons.js:71:13)
    at Socket._writeGeneric (net.js:707:5)
    at Socket._write (net.js:719:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at Connection.write (node_modules/mongodb-core/lib/connection/connection.js:246:21)
    at /project/node_modules/mongodb-core/lib/connection/pool.js:1175:40
    at /project/node_modules/mongodb-core/lib/connection/pool.js:945:23
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by rjrodger** [comment]
@rodmaz thanks - could you submit a reproduction to https://github.com/senecajs/repro as a PR to help debug this

**Comment by rodmaz** [comment]
I still have to write a small reproduction showing this problem. What I can easily see now is that there is a conflict w/ MongoDB NodeJS driver. My MongoDB server uses port 27017.
Whenever I use seneca@3.8.x, some MongoDB driver functions simply do not return. When I downgrade to seneca@3.7.0 everything works fine.
Any guess what my be causing this conflict?

**Comment by rodmaz** [comment]
@rjrodger Is Seneca using somehow the port 27017 (which is default of MongoDB)? I just retested this using Seneca@3.11.0 and the problem is still there.
Apparently microservices using Seneca cannot run together with MongoDB clients.

**Comment by rodmaz** [comment]
@rjrodger Another look into this and I realised that in fact `seneca@3.7.0` started showing this bug. `seneca@3.6.x` works fine.
I also changed the MongoDB port to something different than 27017 and the problem still persists, so this is nothing related to port conflict.

**Comment by rodmaz** [comment]
@rjrodger What has changed from version `3.6.0` to `3.7.0` to cause such an impact/conflict on NodeJS streams?
Another bizarre behaviour is that I cannot reproduce the problem when I run unit tests on my microservice. They all connect to Seneca, query database and work properly with latest `Seneca@3.11.0`. Only when my microservice is receiving requests from outside (load balancer), it crashes when querying MongoDB when using Seneca@3.7.0 or later

**Comment by rjrodger** [comment]
To debug this I would create a simple version of your service that does not use Seneca at all and see if the problem persists. Alternatively use a form of binary search exclusion - disable ahlf your code, test, repeat, until you can narrow down the cause.

**Comment by zhonggithub** [comment]
same issues

use seneca-extended,  seneca@3.7.0 or later.
when i accessing redis,  then same error happen

**Comment by dpinart-uxland** [comment]
Same issues.
I have recently added seneca to my project and since then I'm getting "Illegal invocation" errors when querying Mongo DB. As others, downgrading to 3.7.0 version it works fine...

**Comment by rodmaz** [comment]
Any news on this issue @rjrodger? Do you still need a demo project or @zhonggithub has provided you one?

**Comment by rodmaz** [comment]
So the answer is *NO*. Seneca `3.20.1` does not fix this issue. In fact, it works in the development environment (`macOS Catalina`) but it fails catastrophically in our CircleCI unit tests with the exact same error.
